CHPL_MAKE_HOME = /home/safl/chapel

TMPDIRNAME = genna
BINNAME = chapel.a

TMPBINNAME = genna/chapel.tmp.a
COMP_GEN_CFLAGS = $(OPT_CFLAGS) $(SPECIALIZE_CFLAGS) $(NO_IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = $(LIB_STATIC_FLAG) 
TAGS_COMMAND = 
CHPLSRC = \
	genna/_main.c \


LIBS =
OPTIMIZE = 1


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.static


