/* chapel.chpl:1 */
static void chpl__init_chapel(int64_t _ln, c_string _fn) {
  c_string modFormatStr;
  c_string modStr;
  _ref_int32_t refIndentLevel = NULL;
  if (chpl__init_chapel_p) {
    goto _exit_chpl__init_chapel;
  }
  modFormatStr = "%*s\n";
  modStr = "chapel";
  printModuleInit(modFormatStr, modStr, INT64(6), INT64(1), "chapel.chpl");
  refIndentLevel = &moduleInitLevel;
  *(refIndentLevel) += INT64(1);
  chpl__init_chapel_p = true;
  somethingelse();
  *(refIndentLevel) -= INT64(1);
  _exit_chpl__init_chapel:;
  return;
}

/* chapel.chpl:1 */
int64_t chpl_gen_main(chpl_main_argument* const _arg) {
  chpl___EndCount this8 = NULL;
  int64_t call_tmp;
  chpl_opaque cast_tmp;
  atomic_int64 _init_class_tmp_;
  atomic_int64 this9;
  atomic_int_least64_t ret;
  atomic_int_least64_t type_tmp;
  _ref_atomic_int_least64_t _ref_tmp_ = NULL;
  atomic_int64 wrap_call_tmp;
  chpl_task_list_p ret2;
  chpl___EndCount wrap_call_tmp2 = NULL;
  call_tmp = sizeof(chpl_chpl___EndCount_object);
  cast_tmp = chpl_here_alloc(call_tmp, INT16(15), INT64(1), "chapel.chpl");
  this8 = ((chpl___EndCount)(cast_tmp));
  ((object)(this8))->chpl__cid = chpl__cid_chpl___EndCount;
  (this8)->i = _init_class_tmp_;
  (this8)->taskCnt = INT64(0);
  (this8)->taskList = NULL;
  ret = type_tmp;
  _ref_tmp_ = &ret;
  atomic_init_int_least64_t(_ref_tmp_, INT64(0));
  (&this9)->_v = ret;
  wrap_call_tmp = _construct_atomic_int64(ret, &this9, INT64(1), "chapel.chpl");
  (this8)->i = wrap_call_tmp;
  (this8)->taskCnt = INT64(0);
  ret2 = NULL;
  (this8)->taskList = ret2;
  wrap_call_tmp2 = _construct__EndCount(&wrap_call_tmp, INT64(0), ret2, this8, INT64(1), "chapel.chpl");
  chpl__init_chapel(INT64(1), "chapel.chpl");
  _waitEndCount2(wrap_call_tmp2, INT64(1), "chapel.chpl");
  chpl__autoDestroyGlobals();
  return INT64(0);
}

/* chapel.chpl:2 */
void cAdd(_ref__real64 res, _ref__real64 in1, _ref__real64 in2) {
  _real64 coerce_tmp;
  _real64 coerce_tmp2;
  _real64 call_tmp;
  coerce_tmp = *(in1);
  coerce_tmp2 = *(in2);
  call_tmp = (coerce_tmp + coerce_tmp2);
  *(res) = call_tmp;
  return;
}

/* chapel.chpl:7 */
void cSubtract(_ref__real64 res, _ref__real64 in1, _ref__real64 in2) {
  _real64 coerce_tmp;
  _real64 coerce_tmp2;
  _real64 call_tmp;
  coerce_tmp = *(in1);
  coerce_tmp2 = *(in2);
  call_tmp = (coerce_tmp - coerce_tmp2);
  *(res) = call_tmp;
  return;
}

/* chapel.chpl:12 */
_real32 simpleReals(_real32 x, _real32 y) {
  _real32 call_tmp;
  call_tmp = (x + y);
  return call_tmp;
}

/* chapel.chpl:17 */
int64_t simpleInts(int64_t x, int64_t y) {
  int64_t call_tmp;
  call_tmp = (x + y);
  return call_tmp;
}

/* chapel.chpl:22 */
_real64 nicestuff(int64_t w, int64_t h, int64_t i) {
  int64_t local_dataParMinGranularity;
  chpl_bool local_dataParIgnoreRunningTasks;
  int64_t local_dataParTasksPerLocale;
  DefaultRectangularArr__real64_2_int64_t_F X = NULL;
  DefaultRectangularArr__real64_2_int64_t_F type_tmp = NULL;
  range_int64_t_bounded_F call_tmp;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_ = NULL;
  range_int64_t_bounded_F call_tmp2;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_2 = NULL;
  DefaultRectangularDom_2_int64_t_F call_tmp3 = NULL;
  _ref_DefaultRectangularDom_2_int64_t_F ret_to_arg_ref_tmp_3 = NULL;
  chpl___RuntimeTypeInfo9 call_tmp4;
  DefaultRectangularDom_2_int64_t_F _runtime_type_tmp_ = NULL;
  _ref_DefaultRectangularArr__real64_2_int64_t_F ret_to_arg_ref_tmp_4 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F Y = NULL;
  DefaultRectangularArr__real64_2_int64_t_F type_tmp2 = NULL;
  range_int64_t_bounded_F call_tmp5;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_5 = NULL;
  range_int64_t_bounded_F call_tmp6;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_6 = NULL;
  DefaultRectangularDom_2_int64_t_F call_tmp7 = NULL;
  _ref_DefaultRectangularDom_2_int64_t_F ret_to_arg_ref_tmp_7 = NULL;
  chpl___RuntimeTypeInfo9 call_tmp8;
  DefaultRectangularDom_2_int64_t_F _runtime_type_tmp_2 = NULL;
  _ref_DefaultRectangularArr__real64_2_int64_t_F ret_to_arg_ref_tmp_8 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F R = NULL;
  DefaultRectangularArr__real64_2_int64_t_F type_tmp3 = NULL;
  range_int64_t_bounded_F call_tmp9;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_9 = NULL;
  range_int64_t_bounded_F call_tmp10;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_10 = NULL;
  DefaultRectangularDom_2_int64_t_F call_tmp11 = NULL;
  _ref_DefaultRectangularDom_2_int64_t_F ret_to_arg_ref_tmp_11 = NULL;
  chpl___RuntimeTypeInfo9 call_tmp12;
  DefaultRectangularDom_2_int64_t_F _runtime_type_tmp_3 = NULL;
  _ref_DefaultRectangularArr__real64_2_int64_t_F ret_to_arg_ref_tmp_12 = NULL;
  _real64 call_tmp13;
  _real64 call_tmp14;
  _real64 res;
  range_int64_t_bounded_F call_tmp15;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_13 = NULL;
  range_int64_t_bounded_F _ic__F0_this;
  int64_t i2;
  int64_t ret;
  int64_t end;
  int64_t ret2;
  int64_t i3;
  DefaultRectangularArr__real64_2_int64_t_F chpl__iter_x1 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F chpl__iter_x2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F chpl__iter_x3 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp_x1 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp_x2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp_x3 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp16 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp17 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp18 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp19 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp20 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F call_tmp21 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret3 = NULL;
  int64_t default_argtasksPerLocale;
  chpl_bool default_argignoreRunning;
  int64_t default_argminIndicesPerTask;
  DefaultRectangularArr__real64_2_int64_t_F this8 = NULL;
  DefaultRectangularDom_2_int64_t_F ret4 = NULL;
  _tuple_2_star_int64_t default_argoffset;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_14 = NULL;
  int64_t _ir_F4_offset_x1;
  int64_t _ir_F4_offset_x2;
  int32_t call_tmp22;
  chpl_localeID_t call_tmp23;
  _ref_chpl_localeID_t ret_to_arg_ref_tmp_15 = NULL;
  chpl_localeID_t call_tmp24;
  locale call_tmp25 = NULL;
  int32_t _virtual_method_tmp_;
  int64_t T;
  chpl_bool call_tmp26;
  locale call_tmp27 = NULL;
  int32_t call_tmp28;
  chpl_localeID_t call_tmp29;
  _ref_chpl_localeID_t ret_to_arg_ref_tmp_16 = NULL;
  chpl_localeID_t call_tmp30;
  locale call_tmp31 = NULL;
  int64_t ret5;
  int64_t const_tmp_x1;
  int64_t const_tmp_x2;
  DefaultRectangularDom_2_int64_t_F this9 = NULL;
  chpl_bool call_tmp32;
  _tuple_2_star_range_int64_t_bounded_F ret6;
  int64_t ret_x1;
  int64_t ret_x2;
  _tuple_2_star_int64_t wrap_call_tmp;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_17 = NULL;
  int64_t numChunks;
  int64_t parDim;
  chpl_bool call_tmp33;
  range_int64_t_bounded_F block_x1;
  range_int64_t_bounded_F block_x2;
  range_int64_t_bounded_F this10;
  range_int64_t_bounded_F wrap_call_tmp2;
  range_int64_t_bounded_F this11;
  range_int64_t_bounded_F wrap_call_tmp3;
  _ref_range_int64_t_bounded_F call_tmp34 = NULL;
  range_int64_t_boundedLow_F call_tmp35;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_18 = NULL;
  _ref_range_int64_t_bounded_F call_tmp36 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_ = NULL;
  DefaultRectangularDom_2_int64_t_F this12 = NULL;
  int64_t call_tmp37;
  range_int64_t_bounded_F call_tmp38;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_19 = NULL;
  _ref_range_int64_t_bounded_F call_tmp39 = NULL;
  range_int64_t_boundedLow_F call_tmp40;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_20 = NULL;
  _ref_range_int64_t_bounded_F call_tmp41 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_2 = NULL;
  DefaultRectangularDom_2_int64_t_F this13 = NULL;
  int64_t call_tmp42;
  range_int64_t_bounded_F call_tmp43;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_21 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret7 = NULL;
  int64_t default_argtasksPerLocale2;
  chpl_bool default_argignoreRunning2;
  int64_t default_argminIndicesPerTask2;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp3 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret8 = NULL;
  int64_t default_argtasksPerLocale3;
  chpl_bool default_argignoreRunning3;
  int64_t default_argminIndicesPerTask3;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp4 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret9 = NULL;
  int64_t default_argtasksPerLocale4;
  chpl_bool default_argignoreRunning4;
  int64_t default_argminIndicesPerTask4;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_ = NULL;
  int64_t call_tmp44;
  chpl_opaque cast_tmp;
  _tuple_2_star_range_int64_t_bounded_F T2;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_2 = NULL;
  int64_t call_tmp45;
  chpl_opaque cast_tmp2;
  _tuple_2_star_range_int64_t_bounded_F T3;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_3 = NULL;
  int64_t call_tmp46;
  chpl_opaque cast_tmp3;
  _tuple_2_star_range_int64_t_bounded_F T4;
  _ref__real64 T5 = NULL;
  _ref__real64 T6 = NULL;
  _ref__real64 T7 = NULL;
  _real64 coerce_tmp5;
  _real64 coerce_tmp6;
  _real64 call_tmp47;
  _real64 call_tmp48;
  _real64 call_tmp49;
  _real64 coerce_tmp7;
  _real64 coerce_tmp8;
  _real64 call_tmp50;
  _real64 call_tmp51;
  _real64 call_tmp52;
  _real64 call_tmp53;
  int64_t T8;
  chpl_opaque call_tmp54;
  chpl_opaque call_tmp55;
  chpl_opaque call_tmp56;
  _tuple_2_star_range_int64_t_bounded_F locBlock;
  range_int64_t_bounded_F this14;
  range_int64_t_bounded_F wrap_call_tmp4;
  range_int64_t_bounded_F this15;
  range_int64_t_bounded_F wrap_call_tmp5;
  _ref_range_int64_t_bounded_F call_tmp57 = NULL;
  range_int64_t_boundedLow_F call_tmp58;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_22 = NULL;
  _ref_range_int64_t_bounded_F call_tmp59 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_3 = NULL;
  DefaultRectangularDom_2_int64_t_F this16 = NULL;
  int64_t call_tmp60;
  range_int64_t_bounded_F call_tmp61;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_23 = NULL;
  _ref_range_int64_t_bounded_F call_tmp62 = NULL;
  range_int64_t_boundedLow_F call_tmp63;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_24 = NULL;
  _ref_range_int64_t_bounded_F call_tmp64 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_4 = NULL;
  DefaultRectangularDom_2_int64_t_F this17 = NULL;
  int64_t call_tmp65;
  range_int64_t_bounded_F call_tmp66;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_25 = NULL;
  chpl___EndCount _coforallCount = NULL;
  chpl___EndCount this18 = NULL;
  int64_t call_tmp67;
  chpl_opaque cast_tmp4;
  atomic_int64 _init_class_tmp_;
  atomic_int64 this19;
  atomic_int_least64_t ret10;
  atomic_int_least64_t type_tmp4;
  _ref_atomic_int_least64_t _ref_tmp_ = NULL;
  atomic_int64 wrap_call_tmp6;
  chpl_task_list_p ret11;
  chpl___EndCount wrap_call_tmp7 = NULL;
  range_int64_t_boundedLow_F call_tmp68;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_26 = NULL;
  range_int64_t_bounded_F call_tmp69;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_27 = NULL;
  range_int64_t_bounded_F _ic__F0_this2;
  int64_t i4;
  int64_t ret12;
  int64_t end2;
  int64_t ret13;
  chpl___EndCount rvfDerefTmp = NULL;
  _tuple_3_star__array_DefaultRectangularArr__real64_2_int64_t_F_DefaultRectangularArr__real64_2_int64_t_F rvfDerefTmp2;
  _class_localscoforall_fn7 _args_forcoforall_fn = NULL;
  int64_t chpl_here_alloc_size;
  chpl_opaque chpl_here_alloc_tmp;
  chpl___EndCount delete_tmp = NULL;
  _ref_atomic_int64 _field_destructor_tmp_ = NULL;
  _ref_atomic_int_least64_t call_tmp70 = NULL;
  chpl_opaque call_tmp71;
  DefaultRectangularArr__real64_2_int64_t_F T9 = NULL;
  SumReduceScanOp__real64 T10 = NULL;
  SumReduceScanOp__real64 this20 = NULL;
  int64_t call_tmp72;
  chpl_opaque cast_tmp5;
  _syncvar_chpl_bool wrap_call_tmp8 = NULL;
  SumReduceScanOp__real64 wrap_call_tmp9 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret14 = NULL;
  int64_t default_argtasksPerLocale5;
  chpl_bool default_argignoreRunning5;
  int64_t default_argminIndicesPerTask5;
  DefaultRectangularArr__real64_2_int64_t_F this21 = NULL;
  DefaultRectangularDom_2_int64_t_F ret15 = NULL;
  _tuple_2_star_int64_t default_argoffset2;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_28 = NULL;
  int64_t _ir_F4_offset_x12;
  int64_t _ir_F4_offset_x22;
  int32_t call_tmp73;
  chpl_localeID_t call_tmp74;
  _ref_chpl_localeID_t ret_to_arg_ref_tmp_29 = NULL;
  chpl_localeID_t call_tmp75;
  locale call_tmp76 = NULL;
  int32_t _virtual_method_tmp_2;
  int64_t T11;
  chpl_bool call_tmp77;
  locale call_tmp78 = NULL;
  int32_t call_tmp79;
  chpl_localeID_t call_tmp80;
  _ref_chpl_localeID_t ret_to_arg_ref_tmp_30 = NULL;
  chpl_localeID_t call_tmp81;
  locale call_tmp82 = NULL;
  int64_t ret16;
  int64_t const_tmp_x12;
  int64_t const_tmp_x22;
  DefaultRectangularDom_2_int64_t_F this22 = NULL;
  chpl_bool call_tmp83;
  _tuple_2_star_range_int64_t_bounded_F ret17;
  int64_t ret_x12;
  int64_t ret_x22;
  _tuple_2_star_int64_t wrap_call_tmp10;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_31 = NULL;
  int64_t numChunks2;
  int64_t parDim2;
  chpl_bool call_tmp84;
  range_int64_t_bounded_F block_x12;
  range_int64_t_bounded_F block_x22;
  range_int64_t_bounded_F this23;
  range_int64_t_bounded_F wrap_call_tmp11;
  range_int64_t_bounded_F this24;
  range_int64_t_bounded_F wrap_call_tmp12;
  _ref_range_int64_t_bounded_F call_tmp85 = NULL;
  range_int64_t_boundedLow_F call_tmp86;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_32 = NULL;
  _ref_range_int64_t_bounded_F call_tmp87 = NULL;
  DefaultRectangularDom_2_int64_t_F this25 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp88 = NULL;
  int64_t call_tmp89;
  range_int64_t_bounded_F call_tmp90;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_33 = NULL;
  _ref_range_int64_t_bounded_F call_tmp91 = NULL;
  range_int64_t_boundedLow_F call_tmp92;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_34 = NULL;
  _ref_range_int64_t_bounded_F call_tmp93 = NULL;
  DefaultRectangularDom_2_int64_t_F this26 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp94 = NULL;
  int64_t call_tmp95;
  range_int64_t_bounded_F call_tmp96;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_35 = NULL;
  SumReduceScanOp__real64 T12 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret18 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _ic__F0_this3 = NULL;
  SumReduceScanOp__real64 this27 = NULL;
  int64_t call_tmp97;
  chpl_opaque cast_tmp6;
  _syncvar_chpl_bool wrap_call_tmp13 = NULL;
  SumReduceScanOp__real64 wrap_call_tmp14 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F this28 = NULL;
  DefaultRectangularDom_2_int64_t_F ret19 = NULL;
  _tuple_2_star_int64_t default_argoffset3;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_36 = NULL;
  range_int64_t_bounded_F _formal_tmp_followThis_x1;
  range_int64_t_bounded_F _formal_tmp_followThis_x2;
  range_int64_t_bounded_F block_x13;
  range_int64_t_bounded_F block_x23;
  range_int64_t_bounded_F this29;
  range_int64_t_bounded_F wrap_call_tmp15;
  range_int64_t_bounded_F this30;
  range_int64_t_bounded_F wrap_call_tmp16;
  _ref_range_int64_t_bounded_F call_tmp98 = NULL;
  _ref_range_int64_t_bounded_F call_tmp99 = NULL;
  DefaultRectangularDom_2_int64_t_F this31 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp100 = NULL;
  int64_t ret20;
  int64_t ret21;
  int64_t call_tmp101;
  _ref_range_int64_t_bounded_F call_tmp102 = NULL;
  DefaultRectangularDom_2_int64_t_F this32 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp103 = NULL;
  int64_t ret22;
  int64_t ret23;
  int64_t call_tmp104;
  range_int64_t_bounded_F call_tmp105;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_37 = NULL;
  _ref_range_int64_t_bounded_F call_tmp106 = NULL;
  _ref_range_int64_t_bounded_F call_tmp107 = NULL;
  DefaultRectangularDom_2_int64_t_F this33 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp108 = NULL;
  int64_t ret24;
  int64_t ret25;
  int64_t call_tmp109;
  _ref_range_int64_t_bounded_F call_tmp110 = NULL;
  DefaultRectangularDom_2_int64_t_F this34 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp111 = NULL;
  int64_t ret26;
  int64_t ret27;
  int64_t call_tmp112;
  range_int64_t_bounded_F call_tmp113;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_38 = NULL;
  range_int64_t_bounded_F _ic__F1_block_x2;
  range_int64_t_bounded_F _ic__F0_this4;
  int64_t i5;
  int64_t ret28;
  int64_t end3;
  int64_t ret29;
  int64_t i6;
  range_int64_t_bounded_F _ic__F0_this5;
  int64_t i7;
  int64_t ret30;
  int64_t end4;
  int64_t ret31;
  DefaultRectangularArr__real64_2_int64_t_F this35 = NULL;
  int64_t sum;
  int64_t ret_x13;
  _ref__tuple_2_star_int64_t ret_ = NULL;
  int64_t call_tmp114;
  int64_t ret_x23;
  _ref__tuple_2_star_int64_t ret_2 = NULL;
  int64_t call_tmp115;
  _ddata__real64 ret32 = NULL;
  _ddata__real64 coerce_tmp9 = NULL;
  _ref__real64 call_tmp116 = NULL;
  _real64 coerce_tmp10;
  ReduceScanOp _parent_destructor_tmp_ = NULL;
  _syncvar_chpl_bool _field_destructor_tmp_2 = NULL;
  chpl_opaque call_tmp117;
  _tuple_2_star_range_int64_t_bounded_F locBlock2;
  range_int64_t_bounded_F this36;
  range_int64_t_bounded_F wrap_call_tmp17;
  range_int64_t_bounded_F this37;
  range_int64_t_bounded_F wrap_call_tmp18;
  _ref_range_int64_t_bounded_F call_tmp118 = NULL;
  range_int64_t_boundedLow_F call_tmp119;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_39 = NULL;
  _ref_range_int64_t_bounded_F call_tmp120 = NULL;
  DefaultRectangularDom_2_int64_t_F this38 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp121 = NULL;
  int64_t call_tmp122;
  range_int64_t_bounded_F call_tmp123;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_40 = NULL;
  _ref_range_int64_t_bounded_F call_tmp124 = NULL;
  range_int64_t_boundedLow_F call_tmp125;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_41 = NULL;
  _ref_range_int64_t_bounded_F call_tmp126 = NULL;
  DefaultRectangularDom_2_int64_t_F this39 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F call_tmp127 = NULL;
  int64_t call_tmp128;
  range_int64_t_bounded_F call_tmp129;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_42 = NULL;
  chpl___EndCount _coforallCount2 = NULL;
  chpl___EndCount this40 = NULL;
  int64_t call_tmp130;
  chpl_opaque cast_tmp7;
  atomic_int64 _init_class_tmp_2;
  atomic_int64 this41;
  atomic_int_least64_t ret33;
  atomic_int_least64_t type_tmp5;
  _ref_atomic_int_least64_t _ref_tmp_2 = NULL;
  atomic_int64 wrap_call_tmp19;
  chpl_task_list_p ret34;
  chpl___EndCount wrap_call_tmp20 = NULL;
  range_int64_t_boundedLow_F call_tmp131;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp_43 = NULL;
  range_int64_t_bounded_F call_tmp132;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_44 = NULL;
  range_int64_t_bounded_F _ic__F0_this6;
  int64_t i8;
  int64_t ret35;
  int64_t end5;
  int64_t ret36;
  _ref__EndCount T13 = NULL;
  _ref_SumReduceScanOp__real64 T14 = NULL;
  _class_localscoforall_fn8 _args_forcoforall_fn2 = NULL;
  int64_t chpl_here_alloc_size2;
  chpl_opaque chpl_here_alloc_tmp2;
  chpl___EndCount delete_tmp2 = NULL;
  _ref_atomic_int64 _field_destructor_tmp_3 = NULL;
  _ref_atomic_int_least64_t call_tmp133 = NULL;
  chpl_opaque call_tmp134;
  _real64 call_tmp135;
  ReduceScanOp _parent_destructor_tmp_2 = NULL;
  _syncvar_chpl_bool _field_destructor_tmp_4 = NULL;
  chpl_opaque call_tmp136;
  _real64 call_tmp137;
  _real64 call_tmp138;
  local_dataParMinGranularity = dataParMinGranularity;
  local_dataParIgnoreRunningTasks = dataParIgnoreRunningTasks;
  local_dataParTasksPerLocale = dataParTasksPerLocale;
  ret_to_arg_ref_tmp_ = &call_tmp;
  _build_range(INT64(0), w, ret_to_arg_ref_tmp_, INT64(24), "chapel.chpl");
  ret_to_arg_ref_tmp_2 = &call_tmp2;
  _build_range(INT64(0), h, ret_to_arg_ref_tmp_2, INT64(24), "chapel.chpl");
  ret_to_arg_ref_tmp_3 = &call_tmp3;
  chpl__ensureDomainExpr3(&call_tmp, &call_tmp2, ret_to_arg_ref_tmp_3, INT64(24), "chapel.chpl");
  call_tmp4 = chpl__buildArrayRuntimeType6(call_tmp3, INT64(24), "chapel.chpl");
  _runtime_type_tmp_ = (&call_tmp4)->dom;
  ret_to_arg_ref_tmp_4 = &type_tmp;
  chpl__convertRuntimeTypeToValue9(_runtime_type_tmp_, ret_to_arg_ref_tmp_4, INT64(24), "chapel.chpl");
  X = type_tmp;
  chpl__autoDestroy4(call_tmp3, INT64(24), "chapel.chpl");
  ret_to_arg_ref_tmp_5 = &call_tmp5;
  _build_range(INT64(0), h, ret_to_arg_ref_tmp_5, INT64(25), "chapel.chpl");
  ret_to_arg_ref_tmp_6 = &call_tmp6;
  _build_range(INT64(0), h, ret_to_arg_ref_tmp_6, INT64(25), "chapel.chpl");
  ret_to_arg_ref_tmp_7 = &call_tmp7;
  chpl__ensureDomainExpr3(&call_tmp5, &call_tmp6, ret_to_arg_ref_tmp_7, INT64(25), "chapel.chpl");
  call_tmp8 = chpl__buildArrayRuntimeType6(call_tmp7, INT64(25), "chapel.chpl");
  _runtime_type_tmp_2 = (&call_tmp8)->dom;
  ret_to_arg_ref_tmp_8 = &type_tmp2;
  chpl__convertRuntimeTypeToValue9(_runtime_type_tmp_2, ret_to_arg_ref_tmp_8, INT64(25), "chapel.chpl");
  Y = type_tmp2;
  chpl__autoDestroy4(call_tmp7, INT64(25), "chapel.chpl");
  ret_to_arg_ref_tmp_9 = &call_tmp9;
  _build_range(INT64(0), h, ret_to_arg_ref_tmp_9, INT64(26), "chapel.chpl");
  ret_to_arg_ref_tmp_10 = &call_tmp10;
  _build_range(INT64(0), h, ret_to_arg_ref_tmp_10, INT64(26), "chapel.chpl");
  ret_to_arg_ref_tmp_11 = &call_tmp11;
  chpl__ensureDomainExpr3(&call_tmp9, &call_tmp10, ret_to_arg_ref_tmp_11, INT64(26), "chapel.chpl");
  call_tmp12 = chpl__buildArrayRuntimeType6(call_tmp11, INT64(26), "chapel.chpl");
  _runtime_type_tmp_3 = (&call_tmp12)->dom;
  ret_to_arg_ref_tmp_12 = &type_tmp3;
  chpl__convertRuntimeTypeToValue9(_runtime_type_tmp_3, ret_to_arg_ref_tmp_12, INT64(26), "chapel.chpl");
  R = type_tmp3;
  chpl__autoDestroy4(call_tmp11, INT64(26), "chapel.chpl");
  call_tmp13 = ((_real64)(INT64(1)));
  chpl___ASSIGN_3(type_tmp, call_tmp13, INT64(27), "chapel.chpl");
  call_tmp14 = ((_real64)(INT64(2)));
  chpl___ASSIGN_3(type_tmp2, call_tmp14, INT64(28), "chapel.chpl");
  res = 0.0;
  ret_to_arg_ref_tmp_13 = &call_tmp15;
  _build_range(INT64(1), i, ret_to_arg_ref_tmp_13, INT64(30), "chapel.chpl");
  _ic__F0_this = call_tmp15;
  ret = (&_ic__F0_this)->_low;
  ret2 = (&_ic__F0_this)->_high;
  end = ret2;
  for (i2 = ret; ((i2 <= end)); i2 += INT64(1)) {
    i3 = i2;
    call_tmp16 = chpl__autoCopy10(X, INT64(31), "chapel.chpl");
    call_tmp17 = chpl__autoCopy10(Y, INT64(31), "chapel.chpl");
    call_tmp18 = chpl__autoCopy10(R, INT64(31), "chapel.chpl");
    call_tmp_x1 = call_tmp16;
    call_tmp_x2 = call_tmp17;
    call_tmp_x3 = call_tmp18;
    call_tmp19 = chpl__autoCopy10(call_tmp16, INT64(31), "chapel.chpl");
    call_tmp20 = chpl__autoCopy10(call_tmp17, INT64(31), "chapel.chpl");
    call_tmp21 = chpl__autoCopy10(call_tmp18, INT64(31), "chapel.chpl");
    chpl__iter_x1 = call_tmp19;
    chpl__iter_x2 = call_tmp20;
    chpl__iter_x3 = call_tmp21;
    coerce_tmp = call_tmp19;
    ret3 = coerce_tmp;
    default_argtasksPerLocale = local_dataParTasksPerLocale;
    default_argignoreRunning = local_dataParIgnoreRunningTasks;
    default_argminIndicesPerTask = local_dataParMinGranularity;
    this8 = ret3;
    ret4 = (this8)->dom;
    ret_to_arg_ref_tmp_14 = &default_argoffset;
    createTuple2(INT64(0), ret_to_arg_ref_tmp_14, INT64(31), "chapel.chpl");
    _ir_F4_offset_x1 = *(default_argoffset + INT64(0));
    _ir_F4_offset_x2 = *(default_argoffset + INT64(1));
    call_tmp22 = chpl_task_getRequestedSubloc();
    ret_to_arg_ref_tmp_15 = &call_tmp23;
    chpl_buildLocaleID(chpl_nodeID, call_tmp22, ret_to_arg_ref_tmp_15, INT64(31), "chapel.chpl");
    call_tmp24 = chpl__initCopy_chpl_rt_localeID_t(call_tmp23);
    call_tmp25 = chpl_localeID_to_locale(&call_tmp24, INT64(31), "chapel.chpl");
    _virtual_method_tmp_ = ((object)(call_tmp25))->chpl__cid;
    ((int64_t(*)(locale, int64_t, c_string))chpl_vmtable[((INT64(8) * _virtual_method_tmp_) + INT64(2))])(call_tmp25, INT64(31), "chapel.chpl");
    call_tmp26 = (default_argtasksPerLocale == INT64(0));
    if (call_tmp26) {
      call_tmp28 = chpl_task_getRequestedSubloc();
      ret_to_arg_ref_tmp_16 = &call_tmp29;
      chpl_buildLocaleID(chpl_nodeID, call_tmp28, ret_to_arg_ref_tmp_16, INT64(31), "chapel.chpl");
      call_tmp30 = chpl__initCopy_chpl_rt_localeID_t(call_tmp29);
      call_tmp31 = chpl_localeID_to_locale(&call_tmp30, INT64(31), "chapel.chpl");
      call_tmp27 = call_tmp31;
      ret5 = (call_tmp27)->maxTaskPar;
      T = ret5;
    } else {
      T = default_argtasksPerLocale;
    }
    this9 = ret4;
    call_tmp32 = chpl_task_getSerial();
    if (call_tmp32) {
      const_tmp_x1 = INT64(1);
      const_tmp_x2 = INT64(-1);
    } else {
      *(ret6 + INT64(0)) = *((this9)->ranges + INT64(0));
      *(ret6 + INT64(1)) = *((this9)->ranges + INT64(1));
      ret_to_arg_ref_tmp_17 = &wrap_call_tmp;
      _computeChunkStuff2(T, default_argignoreRunning, default_argminIndicesPerTask, &ret6, ret_to_arg_ref_tmp_17, INT64(31), "chapel.chpl");
      ret_x1 = *(wrap_call_tmp + INT64(0));
      ret_x2 = *(wrap_call_tmp + INT64(1));
      const_tmp_x1 = ret_x1;
      const_tmp_x2 = ret_x2;
    }
    numChunks = const_tmp_x1;
    parDim = const_tmp_x2;
    call_tmp33 = (const_tmp_x1 == INT64(1));
    if (call_tmp33) {
      (&this10)->_low = INT64(0);
      (&this10)->_high = INT64(0);
      (&this10)->_stride = INT64(0);
      (&this10)->_alignment = INT64(0);
      (&this10)->_aligned = false;
      (&this10)->_low = INT64(1);
      (&this10)->_high = INT64(0);
      (&this10)->_stride = INT64(1);
      (&this10)->_alignment = INT64(0);
      (&this10)->_aligned = false;
      wrap_call_tmp2 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this10, INT64(31), "chapel.chpl");
      (&this11)->_low = INT64(0);
      (&this11)->_high = INT64(0);
      (&this11)->_stride = INT64(0);
      (&this11)->_alignment = INT64(0);
      (&this11)->_aligned = false;
      (&this11)->_low = INT64(1);
      (&this11)->_high = INT64(0);
      (&this11)->_stride = INT64(1);
      (&this11)->_alignment = INT64(0);
      (&this11)->_aligned = false;
      wrap_call_tmp3 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this11, INT64(31), "chapel.chpl");
      block_x1 = wrap_call_tmp2;
      block_x2 = wrap_call_tmp3;
      call_tmp34 = &block_x1;
      ret_to_arg_ref_tmp_18 = &call_tmp35;
      _build_range2(_ir_F4_offset_x1, ret_to_arg_ref_tmp_18, INT64(31), "chapel.chpl");
      this12 = ret4;
      _this_tmp_ = &((this12)->ranges);
      call_tmp36 = (*(_this_tmp_) + INT64(0));
      call_tmp37 = length(call_tmp36, INT64(31), "chapel.chpl");
      ret_to_arg_ref_tmp_19 = &call_tmp38;
      chpl___POUND_(&call_tmp35, call_tmp37, ret_to_arg_ref_tmp_19, INT64(31), "chapel.chpl");
      *(call_tmp34) = call_tmp38;
      call_tmp39 = &block_x2;
      ret_to_arg_ref_tmp_20 = &call_tmp40;
      _build_range2(_ir_F4_offset_x2, ret_to_arg_ref_tmp_20, INT64(31), "chapel.chpl");
      this13 = ret4;
      _this_tmp_2 = &((this13)->ranges);
      call_tmp41 = (*(_this_tmp_2) + INT64(1));
      call_tmp42 = length(call_tmp41, INT64(31), "chapel.chpl");
      ret_to_arg_ref_tmp_21 = &call_tmp43;
      chpl___POUND_(&call_tmp40, call_tmp42, ret_to_arg_ref_tmp_21, INT64(31), "chapel.chpl");
      *(call_tmp39) = call_tmp43;
      coerce_tmp2 = call_tmp19;
      ret7 = coerce_tmp2;
      default_argtasksPerLocale2 = local_dataParTasksPerLocale;
      default_argignoreRunning2 = local_dataParIgnoreRunningTasks;
      default_argminIndicesPerTask2 = local_dataParMinGranularity;
      coerce_tmp3 = call_tmp20;
      ret8 = coerce_tmp3;
      default_argtasksPerLocale3 = local_dataParTasksPerLocale;
      default_argignoreRunning3 = local_dataParIgnoreRunningTasks;
      default_argminIndicesPerTask3 = local_dataParMinGranularity;
      coerce_tmp4 = call_tmp21;
      ret9 = coerce_tmp4;
      default_argtasksPerLocale4 = local_dataParTasksPerLocale;
      default_argignoreRunning4 = local_dataParIgnoreRunningTasks;
      default_argminIndicesPerTask4 = local_dataParMinGranularity;
      call_tmp44 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
      cast_tmp = chpl_here_alloc(call_tmp44, INT16(38), INT64(31), "chapel.chpl");
      _ic_ = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp));
      ((object)(_ic_))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
      (_ic_)->more = INT64(1);
      (_ic_)->F0_this = ret7;
      *(T2 + INT64(0)) = block_x1;
      *(T2 + INT64(1)) = block_x2;
      *((_ic_)->F1_followThis + INT64(0)) = *(T2 + INT64(0));
      *((_ic_)->F1_followThis + INT64(1)) = *(T2 + INT64(1));
      (_ic_)->F2_tasksPerLocale = default_argtasksPerLocale2;
      (_ic_)->F3_ignoreRunning = default_argignoreRunning2;
      (_ic_)->F4_minIndicesPerTask = default_argminIndicesPerTask2;
      call_tmp45 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
      cast_tmp2 = chpl_here_alloc(call_tmp45, INT16(38), INT64(31), "chapel.chpl");
      _ic_2 = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp2));
      ((object)(_ic_2))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
      (_ic_2)->more = INT64(1);
      (_ic_2)->F0_this = ret8;
      *(T3 + INT64(0)) = block_x1;
      *(T3 + INT64(1)) = block_x2;
      *((_ic_2)->F1_followThis + INT64(0)) = *(T3 + INT64(0));
      *((_ic_2)->F1_followThis + INT64(1)) = *(T3 + INT64(1));
      (_ic_2)->F2_tasksPerLocale = default_argtasksPerLocale3;
      (_ic_2)->F3_ignoreRunning = default_argignoreRunning3;
      (_ic_2)->F4_minIndicesPerTask = default_argminIndicesPerTask3;
      call_tmp46 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
      cast_tmp3 = chpl_here_alloc(call_tmp46, INT16(38), INT64(31), "chapel.chpl");
      _ic_3 = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp3));
      ((object)(_ic_3))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
      (_ic_3)->more = INT64(1);
      (_ic_3)->F0_this = ret9;
      *(T4 + INT64(0)) = block_x1;
      *(T4 + INT64(1)) = block_x2;
      *((_ic_3)->F1_followThis + INT64(0)) = *(T4 + INT64(0));
      *((_ic_3)->F1_followThis + INT64(1)) = *(T4 + INT64(1));
      (_ic_3)->F2_tasksPerLocale = default_argtasksPerLocale4;
      (_ic_3)->F3_ignoreRunning = default_argignoreRunning4;
      (_ic_3)->F4_minIndicesPerTask = default_argminIndicesPerTask4;
      advance(_ic_, INT64(31), "chapel.chpl");
      advance(_ic_2, INT64(31), "chapel.chpl");
      advance(_ic_3, INT64(31), "chapel.chpl");
      for (; (T8 = (_ic_)->more,T8); ) {
        T5 = (_ic_3)->value;
        T6 = (_ic_2)->value;
        T7 = (_ic_)->value;
        coerce_tmp5 = *(T6);
        coerce_tmp6 = *(T7);
        call_tmp47 = (coerce_tmp5 - coerce_tmp6);
        call_tmp48 = ((_real64)(INT64(2)));
        call_tmp49 = (call_tmp47 * call_tmp48);
        coerce_tmp7 = *(T6);
        coerce_tmp8 = *(T7);
        call_tmp50 = (coerce_tmp7 - coerce_tmp8);
        call_tmp51 = ((_real64)(INT64(3)));
        call_tmp52 = (call_tmp50 * call_tmp51);
        call_tmp53 = (call_tmp49 / call_tmp52);
        *(T5) = call_tmp53;
        advance(_ic_, INT64(31), "chapel.chpl");
        advance(_ic_2, INT64(31), "chapel.chpl");
        advance(_ic_3, INT64(31), "chapel.chpl");
      }
      call_tmp54 = ((void*)(_ic_));
      chpl_here_free(call_tmp54, INT64(31), "chapel.chpl");
      call_tmp55 = ((void*)(_ic_2));
      chpl_here_free(call_tmp55, INT64(31), "chapel.chpl");
      call_tmp56 = ((void*)(_ic_3));
      chpl_here_free(call_tmp56, INT64(31), "chapel.chpl");
    } else {
      (&this14)->_low = INT64(0);
      (&this14)->_high = INT64(0);
      (&this14)->_stride = INT64(0);
      (&this14)->_alignment = INT64(0);
      (&this14)->_aligned = false;
      (&this14)->_low = INT64(1);
      (&this14)->_high = INT64(0);
      (&this14)->_stride = INT64(1);
      (&this14)->_alignment = INT64(0);
      (&this14)->_aligned = false;
      wrap_call_tmp4 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this14, INT64(31), "chapel.chpl");
      (&this15)->_low = INT64(0);
      (&this15)->_high = INT64(0);
      (&this15)->_stride = INT64(0);
      (&this15)->_alignment = INT64(0);
      (&this15)->_aligned = false;
      (&this15)->_low = INT64(1);
      (&this15)->_high = INT64(0);
      (&this15)->_stride = INT64(1);
      (&this15)->_alignment = INT64(0);
      (&this15)->_aligned = false;
      wrap_call_tmp5 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this15, INT64(31), "chapel.chpl");
      *(locBlock + INT64(0)) = wrap_call_tmp4;
      *(locBlock + INT64(1)) = wrap_call_tmp5;
      call_tmp57 = (locBlock + INT64(0));
      ret_to_arg_ref_tmp_22 = &call_tmp58;
      _build_range2(_ir_F4_offset_x1, ret_to_arg_ref_tmp_22, INT64(31), "chapel.chpl");
      this16 = ret4;
      _this_tmp_3 = &((this16)->ranges);
      call_tmp59 = (*(_this_tmp_3) + INT64(0));
      call_tmp60 = length(call_tmp59, INT64(31), "chapel.chpl");
      ret_to_arg_ref_tmp_23 = &call_tmp61;
      chpl___POUND_(&call_tmp58, call_tmp60, ret_to_arg_ref_tmp_23, INT64(31), "chapel.chpl");
      *(call_tmp57) = call_tmp61;
      call_tmp62 = (locBlock + INT64(1));
      ret_to_arg_ref_tmp_24 = &call_tmp63;
      _build_range2(_ir_F4_offset_x2, ret_to_arg_ref_tmp_24, INT64(31), "chapel.chpl");
      this17 = ret4;
      _this_tmp_4 = &((this17)->ranges);
      call_tmp64 = (*(_this_tmp_4) + INT64(1));
      call_tmp65 = length(call_tmp64, INT64(31), "chapel.chpl");
      ret_to_arg_ref_tmp_25 = &call_tmp66;
      chpl___POUND_(&call_tmp63, call_tmp65, ret_to_arg_ref_tmp_25, INT64(31), "chapel.chpl");
      *(call_tmp62) = call_tmp66;
      call_tmp67 = sizeof(chpl_chpl___EndCount_object);
      cast_tmp4 = chpl_here_alloc(call_tmp67, INT16(15), INT64(31), "chapel.chpl");
      this18 = ((chpl___EndCount)(cast_tmp4));
      ((object)(this18))->chpl__cid = chpl__cid_chpl___EndCount;
      (this18)->i = _init_class_tmp_;
      (this18)->taskCnt = INT64(0);
      (this18)->taskList = NULL;
      ret10 = type_tmp4;
      _ref_tmp_ = &ret10;
      atomic_init_int_least64_t(_ref_tmp_, INT64(0));
      (&this19)->_v = ret10;
      wrap_call_tmp6 = _construct_atomic_int64(ret10, &this19, INT64(31), "chapel.chpl");
      (this18)->i = wrap_call_tmp6;
      (this18)->taskCnt = INT64(0);
      ret11 = NULL;
      (this18)->taskList = ret11;
      wrap_call_tmp7 = _construct__EndCount(&wrap_call_tmp6, INT64(0), ret11, this18, INT64(31), "chapel.chpl");
      _coforallCount = wrap_call_tmp7;
      ret_to_arg_ref_tmp_26 = &call_tmp68;
      _build_range2(INT64(0), ret_to_arg_ref_tmp_26, INT64(31), "chapel.chpl");
      ret_to_arg_ref_tmp_27 = &call_tmp69;
      chpl___POUND_(&call_tmp68, const_tmp_x1, ret_to_arg_ref_tmp_27, INT64(31), "chapel.chpl");
      _ic__F0_this2 = call_tmp69;
      ret12 = (&_ic__F0_this2)->_low;
      ret13 = (&_ic__F0_this2)->_high;
      end2 = ret13;
      for (i4 = ret12; ((i4 <= end2)); i4 += INT64(1)) {
        _upEndCount(_coforallCount, INT64(31), "chapel.chpl");
        rvfDerefTmp = _coforallCount;
        *(rvfDerefTmp2 + INT64(0)) = chpl__iter_x1;
        *(rvfDerefTmp2 + INT64(1)) = chpl__iter_x2;
        *(rvfDerefTmp2 + INT64(2)) = chpl__iter_x3;
        chpl_here_alloc_size = sizeof(chpl__class_localscoforall_fn7_object);
        chpl_here_alloc_tmp = chpl_here_alloc(chpl_here_alloc_size, INT16(42), INT64(31), "chapel.chpl");
        _args_forcoforall_fn = ((_class_localscoforall_fn7)(chpl_here_alloc_tmp));
        *((_args_forcoforall_fn)->_0_locBlock + INT64(0)) = *(locBlock + INT64(0));
        *((_args_forcoforall_fn)->_0_locBlock + INT64(1)) = *(locBlock + INT64(1));
        (_args_forcoforall_fn)->_1_parDim = parDim;
        (_args_forcoforall_fn)->_2_numChunks = numChunks;
        (_args_forcoforall_fn)->_3_chunk = i4;
        (_args_forcoforall_fn)->_4_rvfDerefTmp = rvfDerefTmp;
        *((_args_forcoforall_fn)->_5_rvfDerefTmp + INT64(0)) = *(rvfDerefTmp2 + INT64(0));
        *((_args_forcoforall_fn)->_5_rvfDerefTmp + INT64(1)) = *(rvfDerefTmp2 + INT64(1));
        *((_args_forcoforall_fn)->_5_rvfDerefTmp + INT64(2)) = *(rvfDerefTmp2 + INT64(2));
        /*** wrapcoforall_fn6 ***/ chpl_taskListAddCoStmt(INT32(-2), INT64(5), ((void*)(_args_forcoforall_fn)), &(((_args_forcoforall_fn)->_4_rvfDerefTmp)->taskList), chpl_nodeID, INT64(31), "chapel.chpl");
      }
      chpl_taskListProcess((_coforallCount)->taskList, INT64(31), "chapel.chpl");
      _waitEndCount(_coforallCount, INT64(31), "chapel.chpl");
      delete_tmp = _coforallCount;
      _field_destructor_tmp_ = &((delete_tmp)->i);
      call_tmp70 = &((_field_destructor_tmp_)->_v);
      atomic_destroy_int_least64_t(call_tmp70);
      call_tmp71 = ((void*)(delete_tmp));
      chpl_here_free(call_tmp71, INT64(31), "chapel.chpl");
    }
    T9 = R;
    call_tmp72 = sizeof(chpl_SumReduceScanOp__real64_object);
    cast_tmp5 = chpl_here_alloc(call_tmp72, INT16(39), INT64(34), "chapel.chpl");
    this20 = ((SumReduceScanOp__real64)(cast_tmp5));
    ((object)(this20))->chpl__cid = chpl__cid_SumReduceScanOp__real64;
    (this20)->value = 0.0;
    wrap_call_tmp8 = _construct__syncvar(false, INT64(34), "chapel.chpl");
    (this20)->value = 0.0;
    wrap_call_tmp9 = _construct_SumReduceScanOp(wrap_call_tmp8, 0.0, this20, INT64(34), "chapel.chpl");
    T10 = wrap_call_tmp9;
    ret14 = T9;
    default_argtasksPerLocale5 = local_dataParTasksPerLocale;
    default_argignoreRunning5 = local_dataParIgnoreRunningTasks;
    default_argminIndicesPerTask5 = local_dataParMinGranularity;
    this21 = ret14;
    ret15 = (this21)->dom;
    ret_to_arg_ref_tmp_28 = &default_argoffset2;
    createTuple2(INT64(0), ret_to_arg_ref_tmp_28, INT64(34), "chapel.chpl");
    _ir_F4_offset_x12 = *(default_argoffset2 + INT64(0));
    _ir_F4_offset_x22 = *(default_argoffset2 + INT64(1));
    call_tmp73 = chpl_task_getRequestedSubloc();
    ret_to_arg_ref_tmp_29 = &call_tmp74;
    chpl_buildLocaleID(chpl_nodeID, call_tmp73, ret_to_arg_ref_tmp_29, INT64(34), "chapel.chpl");
    call_tmp75 = chpl__initCopy_chpl_rt_localeID_t(call_tmp74);
    call_tmp76 = chpl_localeID_to_locale(&call_tmp75, INT64(34), "chapel.chpl");
    _virtual_method_tmp_2 = ((object)(call_tmp76))->chpl__cid;
    ((int64_t(*)(locale, int64_t, c_string))chpl_vmtable[((INT64(8) * _virtual_method_tmp_2) + INT64(2))])(call_tmp76, INT64(34), "chapel.chpl");
    call_tmp77 = (default_argtasksPerLocale5 == INT64(0));
    if (call_tmp77) {
      call_tmp79 = chpl_task_getRequestedSubloc();
      ret_to_arg_ref_tmp_30 = &call_tmp80;
      chpl_buildLocaleID(chpl_nodeID, call_tmp79, ret_to_arg_ref_tmp_30, INT64(34), "chapel.chpl");
      call_tmp81 = chpl__initCopy_chpl_rt_localeID_t(call_tmp80);
      call_tmp82 = chpl_localeID_to_locale(&call_tmp81, INT64(34), "chapel.chpl");
      call_tmp78 = call_tmp82;
      ret16 = (call_tmp78)->maxTaskPar;
      T11 = ret16;
    } else {
      T11 = default_argtasksPerLocale5;
    }
    this22 = ret15;
    call_tmp83 = chpl_task_getSerial();
    if (call_tmp83) {
      const_tmp_x12 = INT64(1);
      const_tmp_x22 = INT64(-1);
    } else {
      *(ret17 + INT64(0)) = *((this22)->ranges + INT64(0));
      *(ret17 + INT64(1)) = *((this22)->ranges + INT64(1));
      ret_to_arg_ref_tmp_31 = &wrap_call_tmp10;
      _computeChunkStuff2(T11, default_argignoreRunning5, default_argminIndicesPerTask5, &ret17, ret_to_arg_ref_tmp_31, INT64(34), "chapel.chpl");
      ret_x12 = *(wrap_call_tmp10 + INT64(0));
      ret_x22 = *(wrap_call_tmp10 + INT64(1));
      const_tmp_x12 = ret_x12;
      const_tmp_x22 = ret_x22;
    }
    numChunks2 = const_tmp_x12;
    parDim2 = const_tmp_x22;
    call_tmp84 = (const_tmp_x12 == INT64(1));
    if (call_tmp84) {
      (&this23)->_low = INT64(0);
      (&this23)->_high = INT64(0);
      (&this23)->_stride = INT64(0);
      (&this23)->_alignment = INT64(0);
      (&this23)->_aligned = false;
      (&this23)->_low = INT64(1);
      (&this23)->_high = INT64(0);
      (&this23)->_stride = INT64(1);
      (&this23)->_alignment = INT64(0);
      (&this23)->_aligned = false;
      wrap_call_tmp11 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this23, INT64(34), "chapel.chpl");
      (&this24)->_low = INT64(0);
      (&this24)->_high = INT64(0);
      (&this24)->_stride = INT64(0);
      (&this24)->_alignment = INT64(0);
      (&this24)->_aligned = false;
      (&this24)->_low = INT64(1);
      (&this24)->_high = INT64(0);
      (&this24)->_stride = INT64(1);
      (&this24)->_alignment = INT64(0);
      (&this24)->_aligned = false;
      wrap_call_tmp12 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this24, INT64(34), "chapel.chpl");
      block_x12 = wrap_call_tmp11;
      block_x22 = wrap_call_tmp12;
      call_tmp85 = &block_x12;
      ret_to_arg_ref_tmp_32 = &call_tmp86;
      _build_range2(_ir_F4_offset_x12, ret_to_arg_ref_tmp_32, INT64(34), "chapel.chpl");
      this25 = ret15;
      call_tmp88 = &((this25)->ranges);
      call_tmp87 = (*(call_tmp88) + INT64(0));
      call_tmp89 = length(call_tmp87, INT64(34), "chapel.chpl");
      ret_to_arg_ref_tmp_33 = &call_tmp90;
      chpl___POUND_(&call_tmp86, call_tmp89, ret_to_arg_ref_tmp_33, INT64(34), "chapel.chpl");
      *(call_tmp85) = call_tmp90;
      call_tmp91 = &block_x22;
      ret_to_arg_ref_tmp_34 = &call_tmp92;
      _build_range2(_ir_F4_offset_x22, ret_to_arg_ref_tmp_34, INT64(34), "chapel.chpl");
      this26 = ret15;
      call_tmp94 = &((this26)->ranges);
      call_tmp93 = (*(call_tmp94) + INT64(1));
      call_tmp95 = length(call_tmp93, INT64(34), "chapel.chpl");
      ret_to_arg_ref_tmp_35 = &call_tmp96;
      chpl___POUND_(&call_tmp92, call_tmp95, ret_to_arg_ref_tmp_35, INT64(34), "chapel.chpl");
      *(call_tmp91) = call_tmp96;
      ret18 = T9;
      _ic__F0_this3 = ret18;
      call_tmp97 = sizeof(chpl_SumReduceScanOp__real64_object);
      cast_tmp6 = chpl_here_alloc(call_tmp97, INT16(39), INT64(34), "chapel.chpl");
      this27 = ((SumReduceScanOp__real64)(cast_tmp6));
      ((object)(this27))->chpl__cid = chpl__cid_SumReduceScanOp__real64;
      (this27)->value = 0.0;
      wrap_call_tmp13 = _construct__syncvar(false, INT64(34), "chapel.chpl");
      (this27)->value = 0.0;
      wrap_call_tmp14 = _construct_SumReduceScanOp(wrap_call_tmp13, 0.0, this27, INT64(34), "chapel.chpl");
      T12 = wrap_call_tmp14;
      this28 = ret18;
      ret19 = (this28)->dom;
      ret_to_arg_ref_tmp_36 = &default_argoffset3;
      createTuple2(INT64(0), ret_to_arg_ref_tmp_36, INT64(34), "chapel.chpl");
      _formal_tmp_followThis_x1 = block_x12;
      _formal_tmp_followThis_x2 = block_x22;
      (&this29)->_low = INT64(0);
      (&this29)->_high = INT64(0);
      (&this29)->_stride = INT64(0);
      (&this29)->_alignment = INT64(0);
      (&this29)->_aligned = false;
      (&this29)->_low = INT64(1);
      (&this29)->_high = INT64(0);
      (&this29)->_stride = INT64(1);
      (&this29)->_alignment = INT64(0);
      (&this29)->_aligned = false;
      wrap_call_tmp15 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this29, INT64(34), "chapel.chpl");
      (&this30)->_low = INT64(0);
      (&this30)->_high = INT64(0);
      (&this30)->_stride = INT64(0);
      (&this30)->_alignment = INT64(0);
      (&this30)->_aligned = false;
      (&this30)->_low = INT64(1);
      (&this30)->_high = INT64(0);
      (&this30)->_stride = INT64(1);
      (&this30)->_alignment = INT64(0);
      (&this30)->_aligned = false;
      wrap_call_tmp16 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this30, INT64(34), "chapel.chpl");
      block_x13 = wrap_call_tmp15;
      block_x23 = wrap_call_tmp16;
      call_tmp98 = &block_x13;
      this31 = ret19;
      call_tmp100 = &((this31)->ranges);
      call_tmp99 = (*(call_tmp100) + INT64(0));
      ret20 = (call_tmp99)->_low;
      ret21 = (&_formal_tmp_followThis_x1)->_low;
      call_tmp101 = (ret20 + ret21);
      this32 = ret19;
      call_tmp103 = &((this32)->ranges);
      call_tmp102 = (*(call_tmp103) + INT64(0));
      ret22 = (call_tmp102)->_low;
      ret23 = (&_formal_tmp_followThis_x1)->_high;
      call_tmp104 = (ret22 + ret23);
      ret_to_arg_ref_tmp_37 = &call_tmp105;
      _build_range(call_tmp101, call_tmp104, ret_to_arg_ref_tmp_37, INT64(34), "chapel.chpl");
      *(call_tmp98) = call_tmp105;
      call_tmp106 = &block_x23;
      this33 = ret19;
      call_tmp108 = &((this33)->ranges);
      call_tmp107 = (*(call_tmp108) + INT64(1));
      ret24 = (call_tmp107)->_low;
      ret25 = (&_formal_tmp_followThis_x2)->_low;
      call_tmp109 = (ret24 + ret25);
      this34 = ret19;
      call_tmp111 = &((this34)->ranges);
      call_tmp110 = (*(call_tmp111) + INT64(1));
      ret26 = (call_tmp110)->_low;
      ret27 = (&_formal_tmp_followThis_x2)->_high;
      call_tmp112 = (ret26 + ret27);
      ret_to_arg_ref_tmp_38 = &call_tmp113;
      _build_range(call_tmp109, call_tmp112, ret_to_arg_ref_tmp_38, INT64(34), "chapel.chpl");
      *(call_tmp106) = call_tmp113;
      _ic__F1_block_x2 = block_x23;
      _ic__F0_this4 = block_x13;
      ret28 = (&_ic__F0_this4)->_low;
      ret29 = (&_ic__F0_this4)->_high;
      end3 = ret29;
      _ic__F0_this5 = _ic__F1_block_x2;
      ret30 = (&_ic__F0_this5)->_low;
      ret31 = (&_ic__F0_this5)->_high;
      end4 = ret31;
      for (i5 = ret28; ((i5 <= end3)); i5 += INT64(1)) {
        i6 = i5;
        this35 = _ic__F0_this3;
        ret_ = &((this35)->blk);
        ret_x13 = *(*(ret_) + INT64(0));
        call_tmp114 = (i6 * ret_x13);
        ret_2 = &((this35)->blk);
        ret_x23 = *(*(ret_2) + INT64(1));
        ret32 = (this35)->shiftedData;
        coerce_tmp9 = ret32;
        for (i7 = ret30; ((i7 <= end4)); i7 += INT64(1)) {
          sum = INT64(0);
          sum += call_tmp114;
          call_tmp115 = (i7 * ret_x23);
          sum += call_tmp115;
          call_tmp116 = (coerce_tmp9 + sum);
          coerce_tmp10 = *(call_tmp116);
          accumulate(T12, coerce_tmp10, INT64(34), "chapel.chpl");
        }
      }
      chpl__reduceCombine(T10, T12, INT64(34), "chapel.chpl");
      _parent_destructor_tmp_ = ((ReduceScanOp)(T12));
      _field_destructor_tmp_2 = (_parent_destructor_tmp_)->lock_DOLLAR_;
      chpl___TILDE__syncvar(_field_destructor_tmp_2);
      chpl_here_free(((void*)(_field_destructor_tmp_2)), INT64(34), "chapel.chpl");
      call_tmp117 = ((void*)(T12));
      chpl_here_free(call_tmp117, INT64(34), "chapel.chpl");
    } else {
      (&this36)->_low = INT64(0);
      (&this36)->_high = INT64(0);
      (&this36)->_stride = INT64(0);
      (&this36)->_alignment = INT64(0);
      (&this36)->_aligned = false;
      (&this36)->_low = INT64(1);
      (&this36)->_high = INT64(0);
      (&this36)->_stride = INT64(1);
      (&this36)->_alignment = INT64(0);
      (&this36)->_aligned = false;
      wrap_call_tmp17 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this36, INT64(34), "chapel.chpl");
      (&this37)->_low = INT64(0);
      (&this37)->_high = INT64(0);
      (&this37)->_stride = INT64(0);
      (&this37)->_alignment = INT64(0);
      (&this37)->_aligned = false;
      (&this37)->_low = INT64(1);
      (&this37)->_high = INT64(0);
      (&this37)->_stride = INT64(1);
      (&this37)->_alignment = INT64(0);
      (&this37)->_aligned = false;
      wrap_call_tmp18 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this37, INT64(34), "chapel.chpl");
      *(locBlock2 + INT64(0)) = wrap_call_tmp17;
      *(locBlock2 + INT64(1)) = wrap_call_tmp18;
      call_tmp118 = (locBlock2 + INT64(0));
      ret_to_arg_ref_tmp_39 = &call_tmp119;
      _build_range2(_ir_F4_offset_x12, ret_to_arg_ref_tmp_39, INT64(34), "chapel.chpl");
      this38 = ret15;
      call_tmp121 = &((this38)->ranges);
      call_tmp120 = (*(call_tmp121) + INT64(0));
      call_tmp122 = length(call_tmp120, INT64(34), "chapel.chpl");
      ret_to_arg_ref_tmp_40 = &call_tmp123;
      chpl___POUND_(&call_tmp119, call_tmp122, ret_to_arg_ref_tmp_40, INT64(34), "chapel.chpl");
      *(call_tmp118) = call_tmp123;
      call_tmp124 = (locBlock2 + INT64(1));
      ret_to_arg_ref_tmp_41 = &call_tmp125;
      _build_range2(_ir_F4_offset_x22, ret_to_arg_ref_tmp_41, INT64(34), "chapel.chpl");
      this39 = ret15;
      call_tmp127 = &((this39)->ranges);
      call_tmp126 = (*(call_tmp127) + INT64(1));
      call_tmp128 = length(call_tmp126, INT64(34), "chapel.chpl");
      ret_to_arg_ref_tmp_42 = &call_tmp129;
      chpl___POUND_(&call_tmp125, call_tmp128, ret_to_arg_ref_tmp_42, INT64(34), "chapel.chpl");
      *(call_tmp124) = call_tmp129;
      call_tmp130 = sizeof(chpl_chpl___EndCount_object);
      cast_tmp7 = chpl_here_alloc(call_tmp130, INT16(15), INT64(34), "chapel.chpl");
      this40 = ((chpl___EndCount)(cast_tmp7));
      ((object)(this40))->chpl__cid = chpl__cid_chpl___EndCount;
      (this40)->i = _init_class_tmp_2;
      (this40)->taskCnt = INT64(0);
      (this40)->taskList = NULL;
      ret33 = type_tmp5;
      _ref_tmp_2 = &ret33;
      atomic_init_int_least64_t(_ref_tmp_2, INT64(0));
      (&this41)->_v = ret33;
      wrap_call_tmp19 = _construct_atomic_int64(ret33, &this41, INT64(34), "chapel.chpl");
      (this40)->i = wrap_call_tmp19;
      (this40)->taskCnt = INT64(0);
      ret34 = NULL;
      (this40)->taskList = ret34;
      wrap_call_tmp20 = _construct__EndCount(&wrap_call_tmp19, INT64(0), ret34, this40, INT64(34), "chapel.chpl");
      _coforallCount2 = wrap_call_tmp20;
      ret_to_arg_ref_tmp_43 = &call_tmp131;
      _build_range2(INT64(0), ret_to_arg_ref_tmp_43, INT64(34), "chapel.chpl");
      ret_to_arg_ref_tmp_44 = &call_tmp132;
      chpl___POUND_(&call_tmp131, const_tmp_x12, ret_to_arg_ref_tmp_44, INT64(34), "chapel.chpl");
      _ic__F0_this6 = call_tmp132;
      ret35 = (&_ic__F0_this6)->_low;
      ret36 = (&_ic__F0_this6)->_high;
      end5 = ret36;
      for (i8 = ret35; ((i8 <= end5)); i8 += INT64(1)) {
        _upEndCount(_coforallCount2, INT64(34), "chapel.chpl");
        T13 = &_coforallCount2;
        T14 = &T10;
        chpl_here_alloc_size2 = sizeof(chpl__class_localscoforall_fn8_object);
        chpl_here_alloc_tmp2 = chpl_here_alloc(chpl_here_alloc_size2, INT16(42), INT64(34), "chapel.chpl");
        _args_forcoforall_fn2 = ((_class_localscoforall_fn8)(chpl_here_alloc_tmp2));
        *((_args_forcoforall_fn2)->_0_locBlock + INT64(0)) = *(locBlock2 + INT64(0));
        *((_args_forcoforall_fn2)->_0_locBlock + INT64(1)) = *(locBlock2 + INT64(1));
        (_args_forcoforall_fn2)->_1_parDim = parDim2;
        (_args_forcoforall_fn2)->_2_numChunks = numChunks2;
        (_args_forcoforall_fn2)->_3_chunk = i8;
        (_args_forcoforall_fn2)->_4__tmp = T13;
        (_args_forcoforall_fn2)->_5_rvfDerefTmp = T9;
        (_args_forcoforall_fn2)->_6__tmp = T14;
        /*** wrapcoforall_fn7 ***/ chpl_taskListAddCoStmt(INT32(-2), INT64(6), ((void*)(_args_forcoforall_fn2)), &((*((_args_forcoforall_fn2)->_4__tmp))->taskList), chpl_nodeID, INT64(34), "chapel.chpl");
      }
      chpl_taskListProcess((_coforallCount2)->taskList, INT64(34), "chapel.chpl");
      _waitEndCount(_coforallCount2, INT64(34), "chapel.chpl");
      delete_tmp2 = _coforallCount2;
      _field_destructor_tmp_3 = &((delete_tmp2)->i);
      call_tmp133 = &((_field_destructor_tmp_3)->_v);
      atomic_destroy_int_least64_t(call_tmp133);
      call_tmp134 = ((void*)(delete_tmp2));
      chpl_here_free(call_tmp134, INT64(34), "chapel.chpl");
    }
    call_tmp135 = generate(T10, INT64(34), "chapel.chpl");
    _parent_destructor_tmp_2 = ((ReduceScanOp)(T10));
    _field_destructor_tmp_4 = (_parent_destructor_tmp_2)->lock_DOLLAR_;
    chpl___TILDE__syncvar(_field_destructor_tmp_4);
    chpl_here_free(((void*)(_field_destructor_tmp_4)), INT64(34), "chapel.chpl");
    call_tmp136 = ((void*)(T10));
    chpl_here_free(call_tmp136, INT64(34), "chapel.chpl");
    call_tmp137 = ((_real64)(i3));
    call_tmp138 = (call_tmp135 / call_tmp137);
    res = call_tmp138;
    chpl__autoDestroy10(call_tmp_x3, INT64(31), "chapel.chpl");
    chpl__autoDestroy10(call_tmp_x2, INT64(31), "chapel.chpl");
    chpl__autoDestroy10(call_tmp_x1, INT64(31), "chapel.chpl");
    chpl__autoDestroy10(chpl__iter_x3, INT64(31), "chapel.chpl");
    chpl__autoDestroy10(chpl__iter_x2, INT64(31), "chapel.chpl");
    chpl__autoDestroy10(chpl__iter_x1, INT64(31), "chapel.chpl");
  }
  chpl__autoDestroy10(R, INT64(26), "chapel.chpl");
  chpl__autoDestroy10(Y, INT64(25), "chapel.chpl");
  chpl__autoDestroy10(X, INT64(24), "chapel.chpl");
  return res;
}

/* ChapelBase.chpl:24 */
static void chpl__autoDestroyGlobals(void) {
  channel_T_dynamic_T local_stderr;
  channel_T_dynamic_T local_stdout;
  channel_F_dynamic_T local_stdin;
  DefaultRectangularDom_1_int64_t_F local_LocaleSpace = NULL;
  DefaultRectangularArr_locale_1_int64_t_F local_chpl_emptyLocales = NULL;
  DefaultRectangularDom_1_int64_t_F local_chpl_emptyLocaleSpace = NULL;
  _ref_channel_F_dynamic_T _destructor_tmp_ = NULL;
  _ref_channel_T_dynamic_T _destructor_tmp_2 = NULL;
  _ref_channel_T_dynamic_T _destructor_tmp_3 = NULL;
  local_stderr = stderr2;
  local_stdout = stdout2;
  local_stdin = stdin2;
  local_LocaleSpace = LocaleSpace;
  local_chpl_emptyLocales = chpl_emptyLocales;
  local_chpl_emptyLocaleSpace = chpl_emptyLocaleSpace;
  chpl__autoDestroy2(local_chpl_emptyLocaleSpace, INT64(93), "/home/safl/chapel/modules/internal/localeModels/flat/LocaleModel.chpl");
  chpl__autoDestroy5(local_chpl_emptyLocales, INT64(94), "/home/safl/chapel/modules/internal/localeModels/flat/LocaleModel.chpl");
  chpl__autoDestroy(defaultDist, INT64(72), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  chpl__autoDestroy5(Locales, INT64(51), "/home/safl/chapel/modules/internal/LocalesArray.chpl");
  chpl__autoDestroy2(local_LocaleSpace, INT64(55), "/home/safl/chapel/modules/internal/LocalesArray.chpl");
  _destructor_tmp_ = &local_stdin;
  chpl___TILDE_channel(_destructor_tmp_, INT64(2186), "/home/safl/chapel/modules/standard/IO.chpl");
  _destructor_tmp_2 = &local_stdout;
  chpl___TILDE_channel2(_destructor_tmp_2, INT64(2187), "/home/safl/chapel/modules/standard/IO.chpl");
  _destructor_tmp_3 = &local_stderr;
  chpl___TILDE_channel2(_destructor_tmp_3, INT64(2188), "/home/safl/chapel/modules/standard/IO.chpl");
  return;
}

/* chapel.chpl:31 */
static void wrapcoforall_fn6(_class_localscoforall_fn7 c) {
  _tuple_2_star_range_int64_t_bounded_F _0_locBlock;
  int64_t _1_parDim;
  int64_t _2_numChunks;
  int64_t _3_chunk;
  chpl___EndCount _4_rvfDerefTmp = NULL;
  _tuple_3_star__array_DefaultRectangularArr__real64_2_int64_t_F_DefaultRectangularArr__real64_2_int64_t_F _5_rvfDerefTmp;
  *(_0_locBlock + INT64(0)) = *((c)->_0_locBlock + INT64(0));
  *(_0_locBlock + INT64(1)) = *((c)->_0_locBlock + INT64(1));
  _1_parDim = (c)->_1_parDim;
  _2_numChunks = (c)->_2_numChunks;
  _3_chunk = (c)->_3_chunk;
  _4_rvfDerefTmp = (c)->_4_rvfDerefTmp;
  *(_5_rvfDerefTmp + INT64(0)) = *((c)->_5_rvfDerefTmp + INT64(0));
  *(_5_rvfDerefTmp + INT64(1)) = *((c)->_5_rvfDerefTmp + INT64(1));
  *(_5_rvfDerefTmp + INT64(2)) = *((c)->_5_rvfDerefTmp + INT64(2));
  coforall_fn7(&_0_locBlock, _1_parDim, _2_numChunks, _3_chunk, _4_rvfDerefTmp, &_5_rvfDerefTmp);
  chpl_here_free(((void*)(c)), INT64(31), "chapel.chpl");
  return;
}

/* chapel.chpl:34 */
static void wrapcoforall_fn7(_class_localscoforall_fn8 c) {
  _tuple_2_star_range_int64_t_bounded_F _0_locBlock;
  int64_t _1_parDim;
  int64_t _2_numChunks;
  int64_t _3_chunk;
  _ref__EndCount _4__tmp = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _5_rvfDerefTmp = NULL;
  _ref_SumReduceScanOp__real64 _6__tmp = NULL;
  *(_0_locBlock + INT64(0)) = *((c)->_0_locBlock + INT64(0));
  *(_0_locBlock + INT64(1)) = *((c)->_0_locBlock + INT64(1));
  _1_parDim = (c)->_1_parDim;
  _2_numChunks = (c)->_2_numChunks;
  _3_chunk = (c)->_3_chunk;
  _4__tmp = (c)->_4__tmp;
  _5_rvfDerefTmp = (c)->_5_rvfDerefTmp;
  _6__tmp = (c)->_6__tmp;
  coforall_fn8(&_0_locBlock, _1_parDim, _2_numChunks, _3_chunk, _4__tmp, _5_rvfDerefTmp, _6__tmp);
  chpl_here_free(((void*)(c)), INT64(34), "chapel.chpl");
  return;
}

/* chapel.chpl:40 */
void somethingelse(void) {
  chpl___EndCount _coforallCount = NULL;
  chpl___EndCount this8 = NULL;
  int64_t call_tmp;
  chpl_opaque cast_tmp;
  atomic_int64 _init_class_tmp_;
  atomic_int64 this9;
  atomic_int_least64_t ret;
  atomic_int_least64_t type_tmp;
  _ref_atomic_int_least64_t _ref_tmp_ = NULL;
  atomic_int64 wrap_call_tmp;
  chpl_task_list_p ret2;
  chpl___EndCount wrap_call_tmp2 = NULL;
  range_int64_t_bounded_F call_tmp2;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_ = NULL;
  range_int64_t_bounded_F _ic__F0_this;
  int64_t i;
  int64_t ret3;
  int64_t end;
  int64_t ret4;
  chpl___EndCount rvfDerefTmp = NULL;
  _class_localscoforall_fn6 _args_forcoforall_fn = NULL;
  int64_t chpl_here_alloc_size;
  chpl_opaque chpl_here_alloc_tmp;
  chpl___EndCount delete_tmp = NULL;
  _ref_atomic_int64 _field_destructor_tmp_ = NULL;
  _ref_atomic_int_least64_t call_tmp3 = NULL;
  chpl_opaque call_tmp4;
  call_tmp = sizeof(chpl_chpl___EndCount_object);
  cast_tmp = chpl_here_alloc(call_tmp, INT16(15), INT64(41), "chapel.chpl");
  this8 = ((chpl___EndCount)(cast_tmp));
  ((object)(this8))->chpl__cid = chpl__cid_chpl___EndCount;
  (this8)->i = _init_class_tmp_;
  (this8)->taskCnt = INT64(0);
  (this8)->taskList = NULL;
  ret = type_tmp;
  _ref_tmp_ = &ret;
  atomic_init_int_least64_t(_ref_tmp_, INT64(0));
  (&this9)->_v = ret;
  wrap_call_tmp = _construct_atomic_int64(ret, &this9, INT64(41), "chapel.chpl");
  (this8)->i = wrap_call_tmp;
  (this8)->taskCnt = INT64(0);
  ret2 = NULL;
  (this8)->taskList = ret2;
  wrap_call_tmp2 = _construct__EndCount(&wrap_call_tmp, INT64(0), ret2, this8, INT64(41), "chapel.chpl");
  _coforallCount = wrap_call_tmp2;
  ret_to_arg_ref_tmp_ = &call_tmp2;
  _build_range(INT64(1), INT64(4), ret_to_arg_ref_tmp_, INT64(41), "chapel.chpl");
  _ic__F0_this = call_tmp2;
  ret3 = (&_ic__F0_this)->_low;
  ret4 = (&_ic__F0_this)->_high;
  end = ret4;
  for (i = ret3; ((i <= end)); i += INT64(1)) {
    _upEndCount(_coforallCount, INT64(41), "chapel.chpl");
    rvfDerefTmp = _coforallCount;
    chpl_here_alloc_size = sizeof(chpl__class_localscoforall_fn6_object);
    chpl_here_alloc_tmp = chpl_here_alloc(chpl_here_alloc_size, INT16(42), INT64(41), "chapel.chpl");
    _args_forcoforall_fn = ((_class_localscoforall_fn6)(chpl_here_alloc_tmp));
    (_args_forcoforall_fn)->_0_rvfDerefTmp = rvfDerefTmp;
    /*** wrapcoforall_fn8 ***/ chpl_taskListAddCoStmt(INT32(-2), INT64(7), ((void*)(_args_forcoforall_fn)), &(((_args_forcoforall_fn)->_0_rvfDerefTmp)->taskList), chpl_nodeID, INT64(41), "chapel.chpl");
  }
  chpl_taskListProcess((_coforallCount)->taskList, INT64(41), "chapel.chpl");
  _waitEndCount(_coforallCount, INT64(41), "chapel.chpl");
  delete_tmp = _coforallCount;
  _field_destructor_tmp_ = &((delete_tmp)->i);
  call_tmp3 = &((_field_destructor_tmp_)->_v);
  atomic_destroy_int_least64_t(call_tmp3);
  call_tmp4 = ((void*)(delete_tmp));
  chpl_here_free(call_tmp4, INT64(41), "chapel.chpl");
  return;
}

/* chapel.chpl:41 */
static void coforall_fn6(chpl___EndCount _coforallCount) {
  chpl_bool T;
  T = true;
  while (T) {
    T = true;
  }
  _downEndCount(_coforallCount, INT64(41), "chapel.chpl");
  return;
}

/* chapel.chpl:41 */
static void wrapcoforall_fn8(_class_localscoforall_fn6 c) {
  chpl___EndCount _0_rvfDerefTmp = NULL;
  _0_rvfDerefTmp = (c)->_0_rvfDerefTmp;
  coforall_fn6(_0_rvfDerefTmp);
  chpl_here_free(((void*)(c)), INT64(41), "chapel.chpl");
  return;
}

/* chapel.chpl:47 */
int64_t woahhh(int64_t x) {
  int64_t call_tmp;
  call_tmp = (x + x);
  return call_tmp;
}

/* DefaultRectangular.chpl:281 */
static void coforall_fn7(_tuple_2_star_range_int64_t_bounded_F* const locBlock, int64_t parDim, int64_t numChunks, int64_t chunk, chpl___EndCount _coforallCount, _tuple_3_star__array_DefaultRectangularArr__real64_2_int64_t_F_DefaultRectangularArr__real64_2_int64_t_F* const chpl__iter) {
  int64_t local_dataParMinGranularity;
  chpl_bool local_dataParIgnoreRunningTasks;
  int64_t local_dataParTasksPerLocale;
  range_int64_t_bounded_F newRet_x1;
  range_int64_t_bounded_F newRet_x2;
  _tuple_2_star_range_int64_t_bounded_F followMe;
  _tuple_2_star_range_int64_t_bounded_F type_tmp;
  range_int64_t_bounded_F this8;
  range_int64_t_bounded_F wrap_call_tmp;
  range_int64_t_bounded_F this9;
  range_int64_t_bounded_F wrap_call_tmp2;
  _tuple_2_star_int64_t const_tmp;
  int64_t _tmp_x1;
  int64_t _tmp_x2;
  _ref_range_int64_t_bounded_F call_tmp = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_ = NULL;
  int64_t call_tmp2;
  _ref_range_int64_t_bounded_F call_tmp3 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_2 = NULL;
  int64_t ret;
  _ref_range_int64_t_bounded_F call_tmp4 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_3 = NULL;
  int64_t ret2;
  _ref_range_int64_t_bounded_F call_tmp5 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_4 = NULL;
  int64_t ret3;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_ = NULL;
  _ref_range_int64_t_bounded_F call_tmp6 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_5 = NULL;
  range_int64_t_bounded_F call_tmp7;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _tmp_x12 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _tmp_x22 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _tmp_x3 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret4 = NULL;
  int64_t default_argtasksPerLocale;
  chpl_bool default_argignoreRunning;
  int64_t default_argminIndicesPerTask;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret5 = NULL;
  int64_t default_argtasksPerLocale2;
  chpl_bool default_argignoreRunning2;
  int64_t default_argminIndicesPerTask2;
  DefaultRectangularArr__real64_2_int64_t_F coerce_tmp3 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret6 = NULL;
  int64_t default_argtasksPerLocale3;
  chpl_bool default_argignoreRunning3;
  int64_t default_argminIndicesPerTask3;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_ = NULL;
  int64_t call_tmp8;
  chpl_opaque cast_tmp;
  _tuple_2_star_range_int64_t_bounded_F T;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_2 = NULL;
  int64_t call_tmp9;
  chpl_opaque cast_tmp2;
  _tuple_2_star_range_int64_t_bounded_F T2;
  _ic_these_DefaultRectangularArr__real64_2_int64_t_F _ic_3 = NULL;
  int64_t call_tmp10;
  chpl_opaque cast_tmp3;
  _tuple_2_star_range_int64_t_bounded_F T3;
  _ref__real64 T4 = NULL;
  _ref__real64 T5 = NULL;
  _ref__real64 T6 = NULL;
  _real64 coerce_tmp4;
  _real64 coerce_tmp5;
  _real64 call_tmp11;
  _real64 call_tmp12;
  _real64 call_tmp13;
  _real64 coerce_tmp6;
  _real64 coerce_tmp7;
  _real64 call_tmp14;
  _real64 call_tmp15;
  _real64 call_tmp16;
  _real64 call_tmp17;
  int64_t T7;
  chpl_opaque call_tmp18;
  chpl_opaque call_tmp19;
  chpl_opaque call_tmp20;
  local_dataParMinGranularity = dataParMinGranularity;
  local_dataParIgnoreRunningTasks = dataParIgnoreRunningTasks;
  local_dataParTasksPerLocale = dataParTasksPerLocale;
  (&this8)->_low = INT64(0);
  (&this8)->_high = INT64(0);
  (&this8)->_stride = INT64(0);
  (&this8)->_alignment = INT64(0);
  (&this8)->_aligned = false;
  (&this8)->_low = INT64(1);
  (&this8)->_high = INT64(0);
  (&this8)->_stride = INT64(1);
  (&this8)->_alignment = INT64(0);
  (&this8)->_aligned = false;
  wrap_call_tmp = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this8, INT64(282), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  (&this9)->_low = INT64(0);
  (&this9)->_high = INT64(0);
  (&this9)->_stride = INT64(0);
  (&this9)->_alignment = INT64(0);
  (&this9)->_aligned = false;
  (&this9)->_low = INT64(1);
  (&this9)->_high = INT64(0);
  (&this9)->_stride = INT64(1);
  (&this9)->_alignment = INT64(0);
  (&this9)->_aligned = false;
  wrap_call_tmp2 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this9, INT64(282), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  *(type_tmp + INT64(0)) = wrap_call_tmp;
  *(type_tmp + INT64(1)) = wrap_call_tmp2;
  *(type_tmp + INT64(0)) = *(*(locBlock) + INT64(0));
  *(type_tmp + INT64(1)) = *(*(locBlock) + INT64(1));
  *(followMe + INT64(0)) = *(*(locBlock) + INT64(0));
  *(followMe + INT64(1)) = *(*(locBlock) + INT64(1));
  _ref_tmp_ = locBlock;
  call_tmp = this6(_ref_tmp_, parDim, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  call_tmp2 = length(call_tmp, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  _ref_tmp_2 = locBlock;
  call_tmp3 = this6(_ref_tmp_2, parDim, INT64(285), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret = (call_tmp3)->_high;
  _ref_tmp_3 = locBlock;
  call_tmp4 = this6(_ref_tmp_3, parDim, INT64(286), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret2 = (call_tmp4)->_low;
  _ref_tmp_4 = locBlock;
  call_tmp5 = this6(_ref_tmp_4, parDim, INT64(287), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret3 = (call_tmp5)->_low;
  ret_to_arg_ref_tmp_ = &const_tmp;
  _computeBlock(call_tmp2, numChunks, chunk, ret, ret2, ret3, ret_to_arg_ref_tmp_, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  _tmp_x1 = *(const_tmp + INT64(0));
  _tmp_x2 = *(const_tmp + INT64(1));
  _ref_tmp_5 = &followMe;
  call_tmp6 = this6(_ref_tmp_5, parDim, INT64(288), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret_to_arg_ref_tmp_2 = &call_tmp7;
  _build_range(_tmp_x1, _tmp_x2, ret_to_arg_ref_tmp_2, INT64(288), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  *(call_tmp6) = call_tmp7;
  newRet_x1 = *(followMe + INT64(0));
  newRet_x2 = *(followMe + INT64(1));
  _tmp_x12 = *(*(chpl__iter) + INT64(0));
  _tmp_x22 = *(*(chpl__iter) + INT64(1));
  _tmp_x3 = *(*(chpl__iter) + INT64(2));
  coerce_tmp = _tmp_x12;
  ret4 = coerce_tmp;
  default_argtasksPerLocale = local_dataParTasksPerLocale;
  default_argignoreRunning = local_dataParIgnoreRunningTasks;
  default_argminIndicesPerTask = local_dataParMinGranularity;
  coerce_tmp2 = _tmp_x22;
  ret5 = coerce_tmp2;
  default_argtasksPerLocale2 = local_dataParTasksPerLocale;
  default_argignoreRunning2 = local_dataParIgnoreRunningTasks;
  default_argminIndicesPerTask2 = local_dataParMinGranularity;
  coerce_tmp3 = _tmp_x3;
  ret6 = coerce_tmp3;
  default_argtasksPerLocale3 = local_dataParTasksPerLocale;
  default_argignoreRunning3 = local_dataParIgnoreRunningTasks;
  default_argminIndicesPerTask3 = local_dataParMinGranularity;
  call_tmp8 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
  cast_tmp = chpl_here_alloc(call_tmp8, INT16(38), INT64(31), "chapel.chpl");
  _ic_ = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp));
  ((object)(_ic_))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
  (_ic_)->more = INT64(1);
  (_ic_)->F0_this = ret4;
  *(T + INT64(0)) = newRet_x1;
  *(T + INT64(1)) = newRet_x2;
  *((_ic_)->F1_followThis + INT64(0)) = *(T + INT64(0));
  *((_ic_)->F1_followThis + INT64(1)) = *(T + INT64(1));
  (_ic_)->F2_tasksPerLocale = default_argtasksPerLocale;
  (_ic_)->F3_ignoreRunning = default_argignoreRunning;
  (_ic_)->F4_minIndicesPerTask = default_argminIndicesPerTask;
  call_tmp9 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
  cast_tmp2 = chpl_here_alloc(call_tmp9, INT16(38), INT64(31), "chapel.chpl");
  _ic_2 = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp2));
  ((object)(_ic_2))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
  (_ic_2)->more = INT64(1);
  (_ic_2)->F0_this = ret5;
  *(T2 + INT64(0)) = newRet_x1;
  *(T2 + INT64(1)) = newRet_x2;
  *((_ic_2)->F1_followThis + INT64(0)) = *(T2 + INT64(0));
  *((_ic_2)->F1_followThis + INT64(1)) = *(T2 + INT64(1));
  (_ic_2)->F2_tasksPerLocale = default_argtasksPerLocale2;
  (_ic_2)->F3_ignoreRunning = default_argignoreRunning2;
  (_ic_2)->F4_minIndicesPerTask = default_argminIndicesPerTask2;
  call_tmp10 = sizeof(chpl__ic_these_DefaultRectangularArr__real64_2_int64_t_F_object);
  cast_tmp3 = chpl_here_alloc(call_tmp10, INT16(38), INT64(31), "chapel.chpl");
  _ic_3 = ((_ic_these_DefaultRectangularArr__real64_2_int64_t_F)(cast_tmp3));
  ((object)(_ic_3))->chpl__cid = chpl__cid__ic_these_DefaultRectangularArr__real64_2_int64_t_F;
  (_ic_3)->more = INT64(1);
  (_ic_3)->F0_this = ret6;
  *(T3 + INT64(0)) = newRet_x1;
  *(T3 + INT64(1)) = newRet_x2;
  *((_ic_3)->F1_followThis + INT64(0)) = *(T3 + INT64(0));
  *((_ic_3)->F1_followThis + INT64(1)) = *(T3 + INT64(1));
  (_ic_3)->F2_tasksPerLocale = default_argtasksPerLocale3;
  (_ic_3)->F3_ignoreRunning = default_argignoreRunning3;
  (_ic_3)->F4_minIndicesPerTask = default_argminIndicesPerTask3;
  advance(_ic_, INT64(31), "chapel.chpl");
  advance(_ic_2, INT64(31), "chapel.chpl");
  advance(_ic_3, INT64(31), "chapel.chpl");
  for (; (T7 = (_ic_)->more,T7); ) {
    T4 = (_ic_3)->value;
    T5 = (_ic_2)->value;
    T6 = (_ic_)->value;
    coerce_tmp4 = *(T5);
    coerce_tmp5 = *(T6);
    call_tmp11 = (coerce_tmp4 - coerce_tmp5);
    call_tmp12 = ((_real64)(INT64(2)));
    call_tmp13 = (call_tmp11 * call_tmp12);
    coerce_tmp6 = *(T5);
    coerce_tmp7 = *(T6);
    call_tmp14 = (coerce_tmp6 - coerce_tmp7);
    call_tmp15 = ((_real64)(INT64(3)));
    call_tmp16 = (call_tmp14 * call_tmp15);
    call_tmp17 = (call_tmp13 / call_tmp16);
    *(T4) = call_tmp17;
    advance(_ic_, INT64(31), "chapel.chpl");
    advance(_ic_2, INT64(31), "chapel.chpl");
    advance(_ic_3, INT64(31), "chapel.chpl");
  }
  call_tmp18 = ((void*)(_ic_));
  chpl_here_free(call_tmp18, INT64(31), "chapel.chpl");
  call_tmp19 = ((void*)(_ic_2));
  chpl_here_free(call_tmp19, INT64(31), "chapel.chpl");
  call_tmp20 = ((void*)(_ic_3));
  chpl_here_free(call_tmp20, INT64(31), "chapel.chpl");
  _downEndCount(_coforallCount, INT64(281), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  return;
}

/* DefaultRectangular.chpl:281 */
static void coforall_fn8(_tuple_2_star_range_int64_t_bounded_F* const locBlock, int64_t parDim, int64_t numChunks, int64_t chunk, _ref__EndCount _coforallCount, DefaultRectangularArr__real64_2_int64_t_F _tmp, _ref_SumReduceScanOp__real64 _tmp2) {
  range_int64_t_bounded_F newRet_x1;
  range_int64_t_bounded_F newRet_x2;
  _tuple_2_star_range_int64_t_bounded_F followMe;
  _tuple_2_star_range_int64_t_bounded_F type_tmp;
  range_int64_t_bounded_F this8;
  range_int64_t_bounded_F wrap_call_tmp;
  range_int64_t_bounded_F this9;
  range_int64_t_bounded_F wrap_call_tmp2;
  _tuple_2_star_int64_t const_tmp;
  int64_t _tmp_x1;
  int64_t _tmp_x2;
  _ref_range_int64_t_bounded_F call_tmp = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_ = NULL;
  int64_t call_tmp2;
  _ref_range_int64_t_bounded_F call_tmp3 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_2 = NULL;
  int64_t ret;
  _ref_range_int64_t_bounded_F call_tmp4 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_3 = NULL;
  int64_t ret2;
  _ref_range_int64_t_bounded_F call_tmp5 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_4 = NULL;
  int64_t ret3;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_ = NULL;
  _ref_range_int64_t_bounded_F call_tmp6 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _ref_tmp_5 = NULL;
  range_int64_t_bounded_F call_tmp7;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_2 = NULL;
  SumReduceScanOp__real64 T = NULL;
  DefaultRectangularArr__real64_2_int64_t_F T2 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F ret4 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F _ic__F0_this = NULL;
  SumReduceScanOp__real64 this10 = NULL;
  int64_t call_tmp8;
  chpl_opaque cast_tmp;
  _syncvar_chpl_bool wrap_call_tmp3 = NULL;
  SumReduceScanOp__real64 wrap_call_tmp4 = NULL;
  DefaultRectangularArr__real64_2_int64_t_F this11 = NULL;
  DefaultRectangularDom_2_int64_t_F ret5 = NULL;
  _tuple_2_star_int64_t default_argoffset;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp_3 = NULL;
  range_int64_t_bounded_F _formal_tmp_followThis_x1;
  range_int64_t_bounded_F _formal_tmp_followThis_x2;
  range_int64_t_bounded_F block_x1;
  range_int64_t_bounded_F block_x2;
  range_int64_t_bounded_F this12;
  range_int64_t_bounded_F wrap_call_tmp5;
  range_int64_t_bounded_F this13;
  range_int64_t_bounded_F wrap_call_tmp6;
  _ref_range_int64_t_bounded_F call_tmp9 = NULL;
  _ref_range_int64_t_bounded_F call_tmp10 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_ = NULL;
  DefaultRectangularDom_2_int64_t_F this14 = NULL;
  int64_t ret6;
  int64_t ret7;
  int64_t call_tmp11;
  _ref_range_int64_t_bounded_F call_tmp12 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_2 = NULL;
  DefaultRectangularDom_2_int64_t_F this15 = NULL;
  int64_t ret8;
  int64_t ret9;
  int64_t call_tmp13;
  range_int64_t_bounded_F call_tmp14;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_4 = NULL;
  _ref_range_int64_t_bounded_F call_tmp15 = NULL;
  _ref_range_int64_t_bounded_F call_tmp16 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_3 = NULL;
  DefaultRectangularDom_2_int64_t_F this16 = NULL;
  int64_t ret10;
  int64_t ret11;
  int64_t call_tmp17;
  _ref_range_int64_t_bounded_F call_tmp18 = NULL;
  _ref__tuple_2_star_range_int64_t_bounded_F _this_tmp_4 = NULL;
  DefaultRectangularDom_2_int64_t_F this17 = NULL;
  int64_t ret12;
  int64_t ret13;
  int64_t call_tmp19;
  range_int64_t_bounded_F call_tmp20;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp_5 = NULL;
  range_int64_t_bounded_F _ic__F1_block_x2;
  range_int64_t_bounded_F _ic__F0_this2;
  int64_t i;
  int64_t ret14;
  int64_t end;
  int64_t ret15;
  int64_t i2;
  range_int64_t_bounded_F _ic__F0_this3;
  int64_t i3;
  int64_t ret16;
  int64_t end2;
  int64_t ret17;
  DefaultRectangularArr__real64_2_int64_t_F this18 = NULL;
  int64_t sum;
  int64_t ret_x1;
  _ref__tuple_2_star_int64_t ret_ = NULL;
  int64_t call_tmp21;
  int64_t ret_x2;
  _ref__tuple_2_star_int64_t ret_2 = NULL;
  int64_t call_tmp22;
  _ddata__real64 ret18 = NULL;
  _ddata__real64 coerce_tmp = NULL;
  _ref__real64 call_tmp23 = NULL;
  _real64 coerce_tmp2;
  SumReduceScanOp__real64 T3 = NULL;
  ReduceScanOp _parent_destructor_tmp_ = NULL;
  _syncvar_chpl_bool _field_destructor_tmp_ = NULL;
  chpl_opaque call_tmp24;
  chpl___EndCount T4 = NULL;
  (&this8)->_low = INT64(0);
  (&this8)->_high = INT64(0);
  (&this8)->_stride = INT64(0);
  (&this8)->_alignment = INT64(0);
  (&this8)->_aligned = false;
  (&this8)->_low = INT64(1);
  (&this8)->_high = INT64(0);
  (&this8)->_stride = INT64(1);
  (&this8)->_alignment = INT64(0);
  (&this8)->_aligned = false;
  wrap_call_tmp = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this8, INT64(282), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  (&this9)->_low = INT64(0);
  (&this9)->_high = INT64(0);
  (&this9)->_stride = INT64(0);
  (&this9)->_alignment = INT64(0);
  (&this9)->_aligned = false;
  (&this9)->_low = INT64(1);
  (&this9)->_high = INT64(0);
  (&this9)->_stride = INT64(1);
  (&this9)->_alignment = INT64(0);
  (&this9)->_aligned = false;
  wrap_call_tmp2 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this9, INT64(282), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  *(type_tmp + INT64(0)) = wrap_call_tmp;
  *(type_tmp + INT64(1)) = wrap_call_tmp2;
  *(type_tmp + INT64(0)) = *(*(locBlock) + INT64(0));
  *(type_tmp + INT64(1)) = *(*(locBlock) + INT64(1));
  *(followMe + INT64(0)) = *(*(locBlock) + INT64(0));
  *(followMe + INT64(1)) = *(*(locBlock) + INT64(1));
  _ref_tmp_ = locBlock;
  call_tmp = this6(_ref_tmp_, parDim, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  call_tmp2 = length(call_tmp, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  _ref_tmp_2 = locBlock;
  call_tmp3 = this6(_ref_tmp_2, parDim, INT64(285), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret = (call_tmp3)->_high;
  _ref_tmp_3 = locBlock;
  call_tmp4 = this6(_ref_tmp_3, parDim, INT64(286), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret2 = (call_tmp4)->_low;
  _ref_tmp_4 = locBlock;
  call_tmp5 = this6(_ref_tmp_4, parDim, INT64(287), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret3 = (call_tmp5)->_low;
  ret_to_arg_ref_tmp_ = &const_tmp;
  _computeBlock(call_tmp2, numChunks, chunk, ret, ret2, ret3, ret_to_arg_ref_tmp_, INT64(283), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  _tmp_x1 = *(const_tmp + INT64(0));
  _tmp_x2 = *(const_tmp + INT64(1));
  _ref_tmp_5 = &followMe;
  call_tmp6 = this6(_ref_tmp_5, parDim, INT64(288), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  ret_to_arg_ref_tmp_2 = &call_tmp7;
  _build_range(_tmp_x1, _tmp_x2, ret_to_arg_ref_tmp_2, INT64(288), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  *(call_tmp6) = call_tmp7;
  newRet_x1 = *(followMe + INT64(0));
  newRet_x2 = *(followMe + INT64(1));
  T2 = _tmp;
  ret4 = T2;
  _ic__F0_this = ret4;
  call_tmp8 = sizeof(chpl_SumReduceScanOp__real64_object);
  cast_tmp = chpl_here_alloc(call_tmp8, INT16(39), INT64(34), "chapel.chpl");
  this10 = ((SumReduceScanOp__real64)(cast_tmp));
  ((object)(this10))->chpl__cid = chpl__cid_SumReduceScanOp__real64;
  (this10)->value = 0.0;
  wrap_call_tmp3 = _construct__syncvar(false, INT64(34), "chapel.chpl");
  (this10)->value = 0.0;
  wrap_call_tmp4 = _construct_SumReduceScanOp(wrap_call_tmp3, 0.0, this10, INT64(34), "chapel.chpl");
  T = wrap_call_tmp4;
  this11 = ret4;
  ret5 = (this11)->dom;
  ret_to_arg_ref_tmp_3 = &default_argoffset;
  createTuple2(INT64(0), ret_to_arg_ref_tmp_3, INT64(34), "chapel.chpl");
  _formal_tmp_followThis_x1 = newRet_x1;
  _formal_tmp_followThis_x2 = newRet_x2;
  (&this12)->_low = INT64(0);
  (&this12)->_high = INT64(0);
  (&this12)->_stride = INT64(0);
  (&this12)->_alignment = INT64(0);
  (&this12)->_aligned = false;
  (&this12)->_low = INT64(1);
  (&this12)->_high = INT64(0);
  (&this12)->_stride = INT64(1);
  (&this12)->_alignment = INT64(0);
  (&this12)->_aligned = false;
  wrap_call_tmp5 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this12, INT64(34), "chapel.chpl");
  (&this13)->_low = INT64(0);
  (&this13)->_high = INT64(0);
  (&this13)->_stride = INT64(0);
  (&this13)->_alignment = INT64(0);
  (&this13)->_aligned = false;
  (&this13)->_low = INT64(1);
  (&this13)->_high = INT64(0);
  (&this13)->_stride = INT64(1);
  (&this13)->_alignment = INT64(0);
  (&this13)->_aligned = false;
  wrap_call_tmp6 = _construct_range(INT64(1), INT64(0), INT64(1), INT64(0), false, &this13, INT64(34), "chapel.chpl");
  block_x1 = wrap_call_tmp5;
  block_x2 = wrap_call_tmp6;
  call_tmp9 = &block_x1;
  this14 = ret5;
  _this_tmp_ = &((this14)->ranges);
  call_tmp10 = (*(_this_tmp_) + INT64(0));
  ret6 = (call_tmp10)->_low;
  ret7 = (&_formal_tmp_followThis_x1)->_low;
  call_tmp11 = (ret6 + ret7);
  this15 = ret5;
  _this_tmp_2 = &((this15)->ranges);
  call_tmp12 = (*(_this_tmp_2) + INT64(0));
  ret8 = (call_tmp12)->_low;
  ret9 = (&_formal_tmp_followThis_x1)->_high;
  call_tmp13 = (ret8 + ret9);
  ret_to_arg_ref_tmp_4 = &call_tmp14;
  _build_range(call_tmp11, call_tmp13, ret_to_arg_ref_tmp_4, INT64(34), "chapel.chpl");
  *(call_tmp9) = call_tmp14;
  call_tmp15 = &block_x2;
  this16 = ret5;
  _this_tmp_3 = &((this16)->ranges);
  call_tmp16 = (*(_this_tmp_3) + INT64(1));
  ret10 = (call_tmp16)->_low;
  ret11 = (&_formal_tmp_followThis_x2)->_low;
  call_tmp17 = (ret10 + ret11);
  this17 = ret5;
  _this_tmp_4 = &((this17)->ranges);
  call_tmp18 = (*(_this_tmp_4) + INT64(1));
  ret12 = (call_tmp18)->_low;
  ret13 = (&_formal_tmp_followThis_x2)->_high;
  call_tmp19 = (ret12 + ret13);
  ret_to_arg_ref_tmp_5 = &call_tmp20;
  _build_range(call_tmp17, call_tmp19, ret_to_arg_ref_tmp_5, INT64(34), "chapel.chpl");
  *(call_tmp15) = call_tmp20;
  _ic__F1_block_x2 = block_x2;
  _ic__F0_this2 = block_x1;
  ret14 = (&_ic__F0_this2)->_low;
  ret15 = (&_ic__F0_this2)->_high;
  end = ret15;
  _ic__F0_this3 = _ic__F1_block_x2;
  ret16 = (&_ic__F0_this3)->_low;
  ret17 = (&_ic__F0_this3)->_high;
  end2 = ret17;
  for (i = ret14; ((i <= end)); i += INT64(1)) {
    i2 = i;
    this18 = _ic__F0_this;
    ret_ = &((this18)->blk);
    ret_x1 = *(*(ret_) + INT64(0));
    call_tmp21 = (i2 * ret_x1);
    ret_2 = &((this18)->blk);
    ret_x2 = *(*(ret_2) + INT64(1));
    ret18 = (this18)->shiftedData;
    coerce_tmp = ret18;
    for (i3 = ret16; ((i3 <= end2)); i3 += INT64(1)) {
      sum = INT64(0);
      sum += call_tmp21;
      call_tmp22 = (i3 * ret_x2);
      sum += call_tmp22;
      call_tmp23 = (coerce_tmp + sum);
      coerce_tmp2 = *(call_tmp23);
      accumulate(T, coerce_tmp2, INT64(34), "chapel.chpl");
    }
  }
  T3 = *(_tmp2);
  chpl__reduceCombine(T3, T, INT64(34), "chapel.chpl");
  _parent_destructor_tmp_ = ((ReduceScanOp)(T));
  _field_destructor_tmp_ = (_parent_destructor_tmp_)->lock_DOLLAR_;
  chpl___TILDE__syncvar(_field_destructor_tmp_);
  chpl_here_free(((void*)(_field_destructor_tmp_)), INT64(34), "chapel.chpl");
  call_tmp24 = ((void*)(T));
  chpl_here_free(call_tmp24, INT64(34), "chapel.chpl");
  T4 = *(_coforallCount);
  _downEndCount(T4, INT64(281), "/home/safl/chapel/modules/internal/DefaultRectangular.chpl");
  return;
}

